apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - issuer-letsencrypt-staging.yaml

helmCharts:
- name: cert-manager
  includeCRDs: true
  version: v1.14.3
  repo: https://charts.jetstack.io
  valuesFile: values-override.yaml
  releaseName: cert-manager
