apiVersion: v1
kind: Secret
metadata:
    name: sonarr-downloads-sabnzbd-creds
    namespace: media
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Muxz60ynr0Z2KCwn6+X4zVqQXivkY+E=,iv:IyA0Fzd4m5FpQ0Nwji5bZvyna4FXGjSo3QiWf75KXv4=,tag:f5xDCFZ1jveILghBvDm3xA==,type:str]
    password: ENC[AES256_GCM,data:UXiLAD1PkGExTa7MLX6zeRXOMYin9IA18A==,iv:wUMjMVn4gXtxsoZsHYL4MbPlgeHiWzXqRI8EEGEoCOU=,tag:G9eKPU0ZjTRbstFDripwJQ==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T02:17:39Z"
    mac: ENC[AES256_GCM,data:w5gsXsSn0a6JnzrWbiWqbwJqPg2WZ6uY/Esmz2lfBM6ghadUM1suFfU81gQUSYuc9wlTQI43AKapIN7I0u5yKK9KctsnFgWocAUYeuLccM7aQrOMJTpPBBC54tudmuQNPaBnSPOxsQDQoqv1EBMMUcN1eWfjOD9j5qRE7/RTcQ0=,iv:3kPfUss5BgIlqedXlMhoSIeQraXODeORRbNAxXQiUpM=,tag:NQMSSlZyLoWS+D5SFnVzcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
