apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: qbittorrent-vpn-media
spec:
  replicas: 0
  selector:
    matchLabels:
      app: qbittorrent-vpn-media
  template:
    metadata:
      labels:
        app: qbittorrent-vpn-media
    spec:
      containers:
      - name: qbittorrent-vpn-media
        # https://hub.docker.com/r/binhex/arch-qbittorrentvpn/tags
        image: binhex/arch-qbittorrentvpn:4.6.5-1-04
        resources:
          requests:
            memory: "4Mi"
            cpu: "250m"
          limits:
            memory: "10Gi"
            cpu: "8000m"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 6881
        - containerPort: 80
        - containerPort: 8118
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
        - name: downloads-nas-hdd
          mountPath: /downloads-hdd
        env:
        - name: VPN_ENABLED
          value: "yes"
        - name: VPN_USER
          valueFrom:
            secretKeyRef:
              name: qbittorrent-vpn-media-secrets
              key: PIA_USER
        - name: VPN_PASS
          valueFrom:
            secretKeyRef:
              name: qbittorrent-vpn-media-secrets
              key: PIA_PASS
        - name: VPN_PROV
          value: "pia"
        - name: VPN_CLIENT
          value: "openvpn"
        - name: ENABLE_PRIVOXY
          value: "no"
        - name: STRICT_PORT_FORWARD
          value: "yes"
        - name: LAN_NETWORK
          value: "10.0.0.0/8"
        - name: NAME_SERVERS
          value: "1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4"
        - name: DEBUG
          value: "false"
        - name: WEBUI_PORT
          value: "80"
        - name: UMASK
          value: "000"
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: downloads-nas-hdd
        nfs:
          server: "10.100.0.1"
          path: /mnt/tank/downloads/qbittorrent-vpn-media
      - name: config
        hostPath:
          path: /lxc-configs/qbittorrent-vpn-media-config # This path contains the same files on all nodes 
          type: DirectoryOrCreate