apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

generators:
  - secret-generator.yaml

replacements:
  - source:
      kind: Secret
      name: qbittorrent-vpn-media-secrets
      fieldPath: stringData.PUBLIC_URI
    targets:
      - select:
          kind: Ingress
          name: qbittorrent-vpn-media
        fieldPaths:
          - spec.rules.0.host
