apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress-route.yaml

generators:
  - secret-generator.yaml

replacements:
  - source:
      kind: Secret
      name: qbittorrent-vpn-media-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: qbittorrent-media
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: Secret
      name: qbittorrent-vpn-media-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: qbittorrent-media-http
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: Secret
      name: qbittorrent-vpn-media-secrets
      fieldPath: stringData.PUBLIC_URI
    targets:
      - select:
          kind: Certificate
          name: qbittorrent-media-cert
        fieldPaths:
          - spec.dnsNames.0