apiVersion: v1
kind: ConfigMap
metadata:
  name: acquis-configmap
data:
  acquis.yaml: |-
    filenames:
      - /var/log/containers/traefik-*_kube-system_*.log
    force_inotify: true
    poll_without_inotify: false
    labels:
      type: containerd
      program: traefik