apiVersion: v1
kind: Secret
metadata:
    name: agent-credentials
    labels:
        k8s-app: crowdsec
        type: lapi
        version: v1
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:3JZXM7cyO/31BMDeIy9EgxFnLMeI/oO6kR2fajcInevNCRclnGuzPow9/4sLJ190,iv:1CbEVPxaoKIbxggPQeRMTaud5kSryydyT9tbmAF4rlA=,tag:6MfAZjPsMWu5bsO9HTIe4w==,type:str]
    password: ENC[AES256_GCM,data:WBRSNiub3nQ/ekreSgQ28sHN6XGKy42qPBGzc1okThpTmFk2LN8lZSYePWocJVny,iv:cQhjCQ9Wks1k+Mt0L+Z5kQr5kojzBRcXF42hSsbVUDE=,tag:qXck4HfMF5wejKS9DP+F1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-27T23:16:15Z"
    mac: ENC[AES256_GCM,data:jOEPANLjl7/CeCGH8ftD0tQtkH1xec/VKbII3/cF783FRVbKb43I+BF372m71+Ju4jbMZkezwR31xjqCUwznqweUKQe2XF9fKQnrxNDcS6xOP0y2GTk0QlMdELmvFYR4rOB2q+UkoyJnG8a7gB6AD8z41+GtvMwud9daaqlHlvg=,iv:NrQKi6zP/lfqa/5AZZOmUXWmYN4I13nlLNRCsbae4yY=,tag:Co9XJ2Tv+fYtantV78FlKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
