apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: crowdsec
  includeCRDs: true
  version: 0.9.12
  repo: https://crowdsecurity.github.io/helm-charts
  valuesFile: values-override.yaml
  releaseName: crowdsec
  