apiVersion: v1
kind: Secret
metadata:
    name: sonarr-radarr-queue-cleaner-secrets
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:e33vRbZK08BV7CUq4lsJtSGhTCzvzBLpFy/MNmZ62hU=,iv:Sb6ygfp9SZB0R6w8uIgmZdiOvlgf7pkdGSb84hMNHf0=,tag:oH9JNeRlyw6UxrhQYwUwwA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:jvdAFTmJ1xaLjCW4swipjZjf85n6GA0xwCrUHNS5U/Q=,iv:ngRGZuon9mTFVIuOUL3ds+Qr9E/k5ypIHj6tE+uih18=,tag:8a76FsdFz05zwCUb7m5rjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-01T07:26:36Z"
    mac: ENC[AES256_GCM,data:QpJx6yrPGb3wjIo5W6HaJA19FlCcvwTvUyDSnyaTUtJiGot0tpDfgAaaeGEaNDdtUI63B/jzZBHNzbVEDBIB7FFa2OuxrxVii6LbhPwrUb59Nga9+OXnV/otyU/LyeAi9xr/gLD3l3hDbk3wvIjnFYx5s+nxOSW/FzTIxGw0MGE=,iv:HgQrHTfbFfa/oDpDH9jvRhIKt4/+3KKHjJKF7L9sk7M=,tag:pQUXTKCVz1Q16AKuV9PAQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
