apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domainnumbers-cert
spec:
  secretName: domainnumbers-cert
  dnsNames: 
    - overwritten-by-secret
    - overwritten-by-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod