apiVersion: v1
kind: Secret
metadata:
    name: portfolio-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:J5os3mrLM7wegpQPr9zC1/JOmYDWvconR4QDrkuHJZOzVW4LX15W6jKjRr2y9YcY,iv:CZeozRY+ajupN+QQXS+DAVSWYf1123CHarOXrdG8SWM=,tag:+H6zhpU1DLf3Sxmx8i8wCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T07:46:58Z"
    mac: ENC[AES256_GCM,data:3al+sYfgLewZ4t/S6zakrxq6QVBHyS6E3dTpRdDdbmxExDgRT6ZRr2WkDBvdp7DA6d08bUIXEsSk0uB/zy5/ZT3FiJ+CXxc2esoy0x01uLoyy+nPfbfwE733HwwWfZqz3YcZbYLjwX3Pr8eoQfyP7mNgLCDsbFiYZ7uLM/SDMkA=,iv:7auCf9gfQMKMq+iGLyuwP0kdUPQOkVdq+yG9klgvmPw=,tag:R3g79Zm0l+ZV0re9na6SSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
