apiVersion: v1
kind: Secret
metadata:
    name: portfolio-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:J5os3mrLM7wegpQPr9zC1/JOmYDWvconR4QDrkuHJZOzVW4LX15W6jKjRr2y9YcY,iv:CZeozRY+ajupN+QQXS+DAVSWYf1123CHarOXrdG8SWM=,tag:+H6zhpU1DLf3Sxmx8i8wCw==,type:str]
    URI: ENC[AES256_GCM,data:fyI+UX3kpWQf46Et,iv:kWKIV62RD4WKMxg1LCbb1dFKEz0o9o0bHFbv4HBHj1I=,tag:UabE7N/IQdNITnf4WO43cg==,type:str]
    URI_WWW: ENC[AES256_GCM,data:+1DkQ/XUsq/N5Ad/sdloTA==,iv:S4R2o9/2UoWtP1fpM0Z7iCp0vtWiQ+2OHBk43KDDAtg=,tag:8CydRKZHRayDhLTew+hphA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T07:20:53Z"
    mac: ENC[AES256_GCM,data:vJfuTYSASW4N903gXEiToPagOV5MI08YKM/SUWOR3ZPR1XotIJhGy+WCWX2X5IwOUpWS3EJs84j36WYAdySXfOLPZa1MQzzMihlTYEjVra3iFpVm66s/04uLMGoOpMLjaf61iNLsCB66axzfg28Nsh3wb1Qp4xh/npx8KLzLMuo=,iv:67dx9Ex6xxyeoBpvH1DrfPzcdAauxbPa0ONQbzzA6DY=,tag:4oecKIueiECC43Ltg06UcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
