apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-cert
spec:
  secretName: vaultwarden-cert
  dnsNames: 
    - placeholder
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod