apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden

    spec:
      containers:
      - name: vaultwarden
        # https://hub.docker.com/r/vaultwarden/server/tags
        image: vaultwarden/server:1.33.2
        # securityContext:
        #   runAsNonRoot: true
        #   runAsUser: 65534
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "2000m"
        ports:
        - containerPort: 80
        env:
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden-secrets
              key: ADMIN_TOKEN
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vaultwarden-secrets
              key: DATABASE_URL
        - name: DATABASE_MAX_CONNS
          value: "20"
        # - name: DATA_FOLDER
        #   value: /data/vaultwarden/data
        # - name: WEB_VAULT_FOLDER
        #   value: /data/vaultwarden/web-vault
        volumeMounts:
        - name: config
          mountPath: /data
      volumes:
      - name: config
        hostPath:
          path: /lxc-configs/vaultwarden-config # This path contains the same files on all nodes 
          type: DirectoryOrCreate
