apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-static-sites-cert
spec:
  commonName: test
  secretName: nginx-static-sites-cert
  dnsNames:
    - mcchickers.com
    - www.mcchickers.com
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod