apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-static-sites-cert
spec:
  secretName: nginx-static-sites-cert
  dnsNames: []
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging