apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-static-sites-cert
spec:
  secretName: nginx-static-sites-cert
  dnsNames: 
    - mcchickers_uri
    - mcchickers_uri_www
    - 08122036_uri
    - 08122036_uri_www
    - catvideo_uri
    - catvideo_uri_www
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging