apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: authentik
spec:
  entryPoints:
    - web
  routes:
    - match: ingress-route-match
      kind: Rule
      services:
        - name: authentik-server
          port: 80
