apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich

    spec:
      containers:
      - name: immich
        # https://github.com/immich-app/immich/releases
        image: ghcr.io/immich-app/immich-server:v1.111.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "6Gi"
            cpu: "6000m"
        ports:
        - containerPort: 3001
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: DB_URL
        - name: REDIS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: REDIS_HOSTNAME
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secrets
              key: REDIS_PASSWORD
        - name: DB_VECTOR_EXTENSION
          value: "pgvector"
        - name: IMMICH_PORT
          value: "3001"
        volumeMounts:
        - name: nas-hdd-immich
          mountPath: /usr/src/app/upload
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: nas-hdd-immich
        nfs:
          server: "10.100.0.1"
          path: /mnt/tank/kubernetes/immich
      - name: localtime
        hostPath:
          path: /etc/localtime
