container_runtime: containerd

config:
  config.yaml.local: |
    db_config:
      type:     postgresql
      user:     crowdsec
      password: ${DB_PASSWORD}
      db_name:  crowdsec
      host:     10.0.20.32
      port:     5432
      sslmode:  require

agent:
  # To specify each pod you want to process logs from (pods present on the node)
  acquisition:
    - namespace: kube-system
      podName: traefik-*
      program: traefik
  env:
    - name: PARSERS
      value: "crowdsecurity/cri-logs"
    - name: COLLECTIONS
      value: "crowdsecurity/traefik Dominic-Wagner/vaultwarden"
    - name: DISABLE_PARSERS
      value: "crowdsecurity/whitelists"
  persistentVolume:
    config:
      enabled: false
lapi:
  dashboard:
    enabled: false
    ingress:
      host: dashboard.local
      enabled: true
  env:
    - name: ENROLL_KEY
      value: ""
    - name: ENROLL_INSTANCE_NAME
      value: "k8s_cluster"
    - name: ENROLL_TAGS
      value: "k8s cluster"
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: DB_PASSWORD
    # If it's a test, we don't want to share signals with CrowdSec so disable the Online API.
    #- name: DISABLE_ONLINE_API
    #  value: "true"
