apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: web
type: Opaque
stringData:
    #ENC[AES256_GCM,data:OpmYp2+qPZ7W2LBO09mNPVAKLzINvvD6EH9w/NLEwQvqJ0jlm3JKd6G2ISf/Ew==,iv:fBwMZW5Kn45oWJ/ybqDyZ+YyXTefIWlD7H3lxufFcmo=,tag:NCPRNLDdKdsbHKNII4bKzw==,type:comment]
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:ByXoOxCBs4MaWl6/qwpOgnPAmlxtC2ZIPV/LKvh2xqu0hZNWTNRZUqDfsyw3iwxYHCCbZz/9+sSwb1XUOReOUuEx0djvrmvIsCzZU0A0AOTXpX+Z,iv:ypWwoyVkqreCREnYlLmi/mYcDNXZfcrwXNkuaxNgTG0=,tag:wWLVewecWw2jGjAg8JJmPA==,type:str]
    #ENC[AES256_GCM,data:2+NR55oRM5HgeQ0f74N/g7SmlkLCGQjkfZfJBZo++wpUvezabTb7WC85OkrMkYrrMvc=,iv:LjOce6euYqrk8ZV3vA252UuMc8drOFsNVPrScJapXoo=,tag:X2nLdZ//w8xImq5Kfdb2CQ==,type:comment]
    #ENC[AES256_GCM,data:MlMyRoUe5BdXM17PAhf0yzZ81Js2lXI4dK0JYCl9zWtnnpl8sUbycbIQcjXdxS2pJAXsRvz5yEDWhw==,iv:hYrXpXxvf8pVOfba/rBrIDphN6Fn5Noa20tHl9mImPs=,tag:wXgsWcUGXihR0+bwqNcsaw==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:JK0MdEyVm3LS9O7ocoCMnVlrWdsVeHusL2Z6UFi9u3iZnWnGuBrfYVF3HU9TlQrlL+gbhVQvoJdL1Ibdfbe2yg==,iv:ygv5MEQa4bdC8nklg5xlbBH02MQVNSsd5V3KjI2nV7M=,tag:W+uFeTYOHHHNZI+7Hj9hsg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:0aOyRgIIKSQblKQKpHG4KVEB6bWo6fls8SKo/aD125iNcBnePhd472CKevv+tOcCPKIAqB4QTj/dUPgf/DlwZQ==,iv:WepELEy8boMK3VwIQ8rKuCOoxi8J8rmSbFnb5P/5Umw=,tag:NaH2lnOxVmR40zCX4msadA==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:MAUJ/ABRMfr8JgJzeEeWEI1DpqQFoL5kzNopPW6YZAhX8dFTY6iOD+/CJ+PGxqSzUJVRkiifTKtiqpolbZO+jA==,iv:2BxTgL5UQp9p2E0R4ocoknT0YzqovIURfePmPnue/9E=,tag:KBxmEu7wxQ+3xT8op24tAw==,type:str]
    #ENC[AES256_GCM,data:pOeovCLzZCSRf66YYwDOookvJGIyDZ7hT2GEbTLYAcdqjpQ=,iv:/g+D00U3TNARURpDW0d5QF918cYUtZ3i6MLBUcWLFJw=,tag:7rPS3N0776bkb53e6oz1Bw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:H/qVVd4KQzUMhoxgmk6dyJHLLzODDXb/MYQ=,iv:NHI/qwSQNLLGTdqaMCIM1E9NaBbbiwmO/BGzIf5kt4c=,tag:jyDBtrQQr+eE+dZFCM5rzA==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmx0RTBHZ3hmYkU1Z0V0
            cExkR0N3aUs0V3pYY1pxMHUwb3BMSG5mQUZjCk5aQXk3OVkwNExoZngwOEpLMkt3
            NENFQ2RiOGFJTTdMb1pSeFpFMkRYYWsKLS0tIExCd0lYNEk5dFFCN2xPTDVnTmsr
            SWVVVnVIVzFIWml2VDNHWktyeVlnN2sKKsTmxlcxJILufP84DgZUOXrsfMzcFo9e
            q9iOaq6qoOZmz3X2XacIikS3xUSe0uK+oy4obTlQjuS+n9Rc6TMbWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T04:27:54Z"
    mac: ENC[AES256_GCM,data:ZFs1kSUC8cRlF0/EwU796jTIo+16IkNbPXrfQiPsY05SLsGmicedsI1MRsqaxsu/JI76E7UT1BUcfVkEjkDJg49DLbTnmk4f45giQkWQMDHSoML7twU9zF6hDEgqCgwNY8JRrXNigdsGrXCeZAYqsKf1hJ/h7jQffynljXiGaTw=,iv:N0BbrrGK0PWq397CwWD6XiOuhZpN4t0gAKFFHW4iR6w=,tag:2OpWA2E8SL518Q1nW5IF1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-config
    namespace: web
type: Opaque
stringData:
    configuration.yml: ENC[AES256_GCM,data:r40x6+fXa5RkMpiNKR0oYWN4RSnx1rLuE6gC55qd3Q9YQJ4+jIyH6mRfvOzbtC6GlrQEyPSQ+n3i2M5X6ZfQkWlvuPEuy1QLpkdGpF6hj0Z6PQsFXT2MJMkyYqQYTQLOQI9VfHQ3/eJ9yEIDf3AWBRbNQQBOVlWYo+h+hwGPEt4MePXKGQVF8yTYKV2fAgH3ltfIHDk6uNphP9DDd3+WrWwksKPkC7d7O5Jxk4ruceISW4S1g3NJUx1ZD1IuJ0Zd5NjjVe59dUyO7xWJGOosCh3JpntfJ4NPAJo/pupP6yX/AMBe4msWSYdq2sGuWf7MghOEtsH0aPRfZvEfCCXvf1NGiYSubVsKB7XSSfoRwx1PDsN1v2QquXy4emLrd0X+4AnQ7kCMvxUAIxOqc1bmKBxJBWP+YoRw86I/YUydiMzT8sbENBjC8VFjm8pDi1xM5D1noeBOlXGcXRcq/6Zphio6wtz20W4u0HejypTyQrBQ6OHAP3KHOVeKwgjV+5cdn2y5B4JOFB8fYwf+7g8X/VbGVFm1ErB5nP0UPykDK93kxsoXfiqMDWdyZpgiKiuUiaZo7oN2lWDqYMQiW8w9sP3wnG3zE97ONukpXhkHY8jbz9EU2B5Z4ETDMsfEcX4WD+gmF2J6YmcDF9TiRrer7VBd1K64LIyzoDY8Pjp4kSv0wjX+FEJx0pdPq91kPs6/26eUYx1hDFVuuJPuzKmOUvZTM809cCO5tA+Twk8DSosAeOdXfDJbO95cUkc8KqSSmDXtRq5FtfPb/HVZDPJVAdIsfZOD5cMECx3OwbvKHSU1mvjNGMx7CACWi4uwlSIkbFPXqmQMAnLAlmiwT/tnTde4gnhS/1iVIwpP7aokc4ZMgW1hpjuZUSsyL9SoU5qQj1XjGnGHWrjkqjjDQIyUwscKklTniSq9lOjchEVObmxrGD7FAY/AYgQLOm46TS1lt0DtiwNCIbNrOHicYLmMYc0cvFZ4l7NVAHRZ4VnsmjKjixhH5bk9aMhiwcimOZNGhIdm3ny1olv8imv25qL9Kun1KhR3m0/H8jcf2EOTcyS2XuYpTQbg2DWyHnvphYcyJx/06Q6kTXuHP32Gbd5mk5rsZlzjJUZvHFxteIUoPmSsBlwcMHp9wyphxx6BuwFOZWctUVEwtpZi/HJ0DX9oRxUOEW/azSnxTdBEaSVBF0YrZ7cLynNw1KQl6SmUGr1smIa0iS0fqvGeogV4+IOiRK5RxsWjM8lhY3dSXOSE0ydcmB1q0ppITPytvQ6QAka2l+krOx1ZZQFSab5joXy9qH2u4hvWFrU55rsFm5WwWmKvwzcd7NJY6e8SaFqOhcC/imLbvDFgW7pAKDMjHtHlYhcLfwm7BKgCUWV5i5bWj9Uc0pUts0UB+29wLUzPQ6FTRUmg1eWRrmLvWg8L6LGTJdAe4qR07En1fapfiodUeoBdI90v9wbbL7Y+lyj2qzgYGA+Q8lgwVdQUu8POkJwJya8BIB1nVDXGZYvRVnnuyIxF4GE2J0r0sdpx0HFpbVdPj2fvp+/xroeT/cXQvHtJBRuyAG2cojU82oxwnWj9eJNcUXPLLBIY359Arysc+TBiMCKN3GgO6emC6R/ChCYAGHpZ6d9wxUEoc62cMagNa/TfPSmNxloCzmQtAGMSbxRJWL9/29REwDidparSmXH3pTqxhEpANqrLAXqLp76aDasvqnMweIE89j+y9R3Gq2DcCqSb1SAmVhC/9pDeqemrpuO5LNjK+yj9gTwqBkZdfjNhbe1QI950+Re9JFB71jLEju5K11xmoh5z8zmYfixREHG0Ys/gDCSkOlSrPizGQ26bugGNwz40ayW/yp/a5ODh/OZx5DHqiZuNJOmaCyPS7Cw5KY1wiHyggX5MQ+UGozgf2YqVYrwfQLY8tu12VL54JE7N+2RwsSluax0sPnLjq/WCVwcR7CHkQWbJh+4sA/TynQXsvKSCEjD8ovpI6tgBkkMmEpvIk9/jalkjxMO9j9kjO7qfN70LUAJ4xMPWW6KLjJFk0ucFm5TWpyQCg4dtwY6oZ26/sjotffChCTPbs9hF9mI7gilLlQRRtUrYW0T/yfDyXzS6W63MOYk0WlQAHZCcIlCuUnsWIRnw1cIC7Ut6IlhLYfcAjN30b/jH8xBKp2dAo2HpP5AzJPUf9Y/88fL1iXNzh9L+HDR4A6fCxRBLBvPJ+vOwpnqrG+NjAI9WTqngnvIfVfWHTh2QVWKjqp6nndTNt2bDZraGjnKEZs/ZVa6CU0BY2w1+LxZMDckRUyuLZa4dxkKrddYEUFTcSiCBcuJwhnbn3vzedmR01JtQ685xevV2+oq8PRcrKZnncY5T7Ym5c44FWPChRsNkTN88pViybLC+LerF2pkqaNUmliwzlifi8BcLhGHWsJpktp0+spdf977gujZqVMJug/HspA+OAVk1P2/Xr/W/8L9a9lA8wVv2ubo4DXRnW17PtZBFS9wdRfTfeJ9YcEvgXizamNhg4h3PjMhaqdQgVEI6EgSK0VTFosPPbfBAcz4RUvk33wytHQBBK2IL3nznwYFIl/6VXbTp/2xrcD7Tt5MCvAan6JgA2mpte9dp/UQhrZW/R2ZSKsnUailoSo64uee0/93rkTsmAADO7if4uEcS4G3XAeeuzu3B4cL6wcmRe8GcLcN8HgJ4syIl9m46TVAwSK0r3QmH0bYZkcVLv9I3klXKrVpkRYAQK3l1/wg/ia+FXEA9HXMGbQtp0aeWPnq+kWSvNCMLrxpa+dOO4VDRI8KJkRcq6MNPEyqquekO4My/yr9AQcii7xLu/r6AMC67xtSRS1KRI+pf3B1J4dQR01thifrfjuHxsZmL9Msr1Sfow2u5NQP9rX8Y21HBAuA7dqyLRn0dM04xrXm98SWWI2CQlV/6hFCvwadiT+DZecZyDitKC2m25slZnTdRHPXgq8WKy/okC9Ncp06a9lgTZyfBgQkDsqQh1wI87wmUI56tkVo6/x9s3dMOvNr7nXj8za7WnzzJAPbh,iv:jvghDinFN30Pp6hdz/A0TrMvcCoNUVxmmU2034V4Izs=,tag:y3DcyVzxTo6krSlUWcDshQ==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmx0RTBHZ3hmYkU1Z0V0
            cExkR0N3aUs0V3pYY1pxMHUwb3BMSG5mQUZjCk5aQXk3OVkwNExoZngwOEpLMkt3
            NENFQ2RiOGFJTTdMb1pSeFpFMkRYYWsKLS0tIExCd0lYNEk5dFFCN2xPTDVnTmsr
            SWVVVnVIVzFIWml2VDNHWktyeVlnN2sKKsTmxlcxJILufP84DgZUOXrsfMzcFo9e
            q9iOaq6qoOZmz3X2XacIikS3xUSe0uK+oy4obTlQjuS+n9Rc6TMbWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T04:27:54Z"
    mac: ENC[AES256_GCM,data:ZFs1kSUC8cRlF0/EwU796jTIo+16IkNbPXrfQiPsY05SLsGmicedsI1MRsqaxsu/JI76E7UT1BUcfVkEjkDJg49DLbTnmk4f45giQkWQMDHSoML7twU9zF6hDEgqCgwNY8JRrXNigdsGrXCeZAYqsKf1hJ/h7jQffynljXiGaTw=,iv:N0BbrrGK0PWq397CwWD6XiOuhZpN4t0gAKFFHW4iR6w=,tag:2OpWA2E8SL518Q1nW5IF1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: web
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:va/WvHWuxx9BtmjAshxv3c2hA3yQ/TqkMvq4Hk9m4Q5sI2zVU80d44F1pkfGJMq8QYfyxDIZwqBLSoBw71CdWMFDMyvK5CpxBRR54qhK/hGlBl+5q9NIXpu8COXOX54RLnmwbQZzDdTgt7sSiJFFz5F69CYV2cprAUV2104pQVaM3VhP8yraBwU4u+SaXqlD+pRow9GRziksmjBlXoXE9wi7lawdOpGrfOxmauq46DvjINVUczxWGg8NsLDyvd7jzoKDpse1Tahwm91HJqPTRiw3ygqTw2fVnrD+lSOj7U/nSmnZfkp0OSzSDpPoJDw0JKlN18Zl/bVI2dwJeig+8GWtyYRAgpkydb50x9utmcim6ej9TijG2Bmxdc5/6WimHTstrIqMImRFYsT2UVPcSwSGdmxxBeITiFu3fkvwcT1tODj2UDLyGeK2AYtC0sg7jS8ACsrWbSni+2iKHLC5oFOl1M82O6A5CMP28iBH23iI7MNMhYTKV9tzAQbxLjU4tml+ZtgODqlCWT3SxHxRioutGXOLM6WEiXdTMNxEonych6MLrlVzOLrKZccS+B1dUzK7AOMnSCWaBA7kwCT0dC4uDvfMF+tUf3ZvbMQvp6zZZjprWviwPYlnlIppHo348kF7wzSI5EUXWBlZyc1ztGVl+CQohfjxZbC0Y//sV3rQKenrha/ldAjYNuA3sqceMDOc27Qn2Bj/RhQZSrh0BcT5tu0b8lKmc/PJycVgo4/XWASh+6qPzo3MweWbfMY7sR2dCWs/grWDgBZsjRlxMu3w5UbqL6sV/TgAoGWVsSkdjPWMg1tJO5PoCmaUDQfalbeCp9p3SCEvLOgCEglcSV5Tf3nK4mZxWFnfIpUapnpMOTMvNHw=,iv:INN9zIUZLmn/UtVCYT24QjpmOQVWKYd8IVDZBfBuS+E=,tag:QXez8ZFTpIIjgo7VNejXGw==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbmx0RTBHZ3hmYkU1Z0V0
            cExkR0N3aUs0V3pYY1pxMHUwb3BMSG5mQUZjCk5aQXk3OVkwNExoZngwOEpLMkt3
            NENFQ2RiOGFJTTdMb1pSeFpFMkRYYWsKLS0tIExCd0lYNEk5dFFCN2xPTDVnTmsr
            SWVVVnVIVzFIWml2VDNHWktyeVlnN2sKKsTmxlcxJILufP84DgZUOXrsfMzcFo9e
            q9iOaq6qoOZmz3X2XacIikS3xUSe0uK+oy4obTlQjuS+n9Rc6TMbWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T04:27:54Z"
    mac: ENC[AES256_GCM,data:ZFs1kSUC8cRlF0/EwU796jTIo+16IkNbPXrfQiPsY05SLsGmicedsI1MRsqaxsu/JI76E7UT1BUcfVkEjkDJg49DLbTnmk4f45giQkWQMDHSoML7twU9zF6hDEgqCgwNY8JRrXNigdsGrXCeZAYqsKf1hJ/h7jQffynljXiGaTw=,iv:N0BbrrGK0PWq397CwWD6XiOuhZpN4t0gAKFFHW4iR6w=,tag:2OpWA2E8SL518Q1nW5IF1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
