apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
  namespace: web
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: n8n-pv
    volumeAttributes:
      source: "//10.100.0.1/pod-configs"
    nodeStageSecretRef:
      name: n8n-smb-creds
      namespace: web