apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:CufW+vLI7NCR4nv+/IPlJWgl716PSdEH,iv:KyMp9yRChSRUSJumbgPh4vaSLoUMzn2TrJt83wxMClM=,tag:jq8bEajgBOnA8bZge2fcog==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:k46jfcRE0N/UCD5TgDOq/bfcGkyyRu8EBA==,iv:9KuJx7LrnZyEdLwurSTd7Mk+Hd94n+UTm/q0Glo3+rs=,tag:28Z3TvGZnbdxi3+IzXfIZg==,type:str]
    DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:fxbzythIbHnf0w==,iv:fACZT7Y9criR42NFjwAnUzM453ANF9Tm3j+yseEVrg0=,tag:l4eD92bO635Alg2xdOHNuw==,type:str]
    DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:P8z0fw==,iv:yG30GMf8MiAi9mNkhRbqaAF8P2O3ZTeWfuPDjZ6gOAA=,tag:JeYSZwaN5xSJLs1refYcVQ==,type:str]
    DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:JEUE,iv:QYVMgvGUHOJ8qilxFsgKbyW5OSgILBDfbvjJ1ZMhN9M=,tag:+8rtPrdaLnU0HhLEKv+mwg==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:/d/Q,iv:gH1kCBMDKFi+0qRvQ4Z31+xw8Rhni6nos0GAPb7A18g=,tag:MYNXcaD7U7VGgGE1sYwWeg==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:z+//Wn5LhBq4uggf7bvRg7DrxON125kj8g==,iv:lx40HfDvQ1m33PYu5FLCHG8FIYCwaIb71Dx1tHD+vZU=,tag:VsZ9Kl/uWZRMulVsOyrmPA==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:P7AuhzwXAIbxFXWszna0E6CoRYtRJayFLqJDM+DXZBqHuts8YwNUJE1Mr15EWE3KOnEIRKnFx36TQomwybWLlw==,iv:sLTPznHoydtX1zsU4Lb8ONDTUeebsJ5FVot38AqXSQ4=,tag:3HNDu5cPMmAIbTDc+h9kJQ==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T05:52:20Z"
    mac: ENC[AES256_GCM,data:ZSvYAwM7gn2h5YQu5SECVxsqlkT9U14xqHEx2XCP+LWsRZ2Xq3IlDgVQSq/cy7WPgh5kiKrCtP2c5TFyXTKE0kEAkBkEor6R5ks/zs9mLYqTycHr8igUKb1AAUeIG+3IbOZlZedFeomnbaPgqJI+S/+SmuBDaVxj4MyOGf6rHJ8=,iv:FzFlPbIGzutreunXwFHE/BooJb2/0iLWvNQWGeWOyao=,tag:H4eZmbl2fx905pfcQ+k5UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: n8n-smb-creds
    namespace: web
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:sxFxf0Z32A6cGZ2n9tDhHW0zsV8=,iv:MPRSFMkqYq4AFp3Ck7DfRftyhAw2iPtwHK4dA0TZ93k=,tag:3xJqTjdIxZBBojLxFop22A==,type:str]
    password: ENC[AES256_GCM,data:J68J1K1EQ1+FhQzQC6XBajet8A8ol1V26w==,iv:/fKvP4pKTf0bhku+Br6BOFSC5/oxQ85H2MRTwpIen/U=,tag:U5lG8o03hkG9GZZoxH+gjA==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T05:52:20Z"
    mac: ENC[AES256_GCM,data:ZSvYAwM7gn2h5YQu5SECVxsqlkT9U14xqHEx2XCP+LWsRZ2Xq3IlDgVQSq/cy7WPgh5kiKrCtP2c5TFyXTKE0kEAkBkEor6R5ks/zs9mLYqTycHr8igUKb1AAUeIG+3IbOZlZedFeomnbaPgqJI+S/+SmuBDaVxj4MyOGf6rHJ8=,iv:FzFlPbIGzutreunXwFHE/BooJb2/0iLWvNQWGeWOyao=,tag:H4eZmbl2fx905pfcQ+k5UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
