apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pterodactyl-panel-cert
spec:
  secretName: pterodactyl-panel-cert
  dnsNames: 
    - placeholder
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging