apiVersion: apps/v1
kind: Deployment
metadata:
  name: pterodactyl-panel
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pterodactyl-panel
  template:
    metadata:
      labels:
        app: pterodactyl-panel

    spec:
      containers:
      - name: pterodactyl-panel
        # https://hub.docker.com/r/ccarney16/pterodactyl-panel/tags
        image: ccarney16/pterodactyl-panel:v1.11.11
        # securityContext:
          # runAsNonRoot: true
          # runAsUser: 498
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "800Mi"
            cpu: "3000m"
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          value: production
        - name: APP_DEBUG
          value: "false"
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: APP_KEY
        - name: APP_THEME
          value: pterodactyl
        - name: APP_TIMEZONE
          value: America/Chicago
        - name: APP_URL
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: APP_URL
        - name: APP_LOCALE
          value: en
        - name: APP_ENVIRONMENT_ONLY
          value: "true"
        - name: LOG_CHANNEL
          value: daily
        - name: LOG_DEPRECATIONS_CHANNEL
          value: "null"
        - name: LOG_LEVEL
          value: debug
        - name: DB_CONNECTION
          value: mysql
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: DB_HOST
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: REDIS_PASSWORD
        - name: REDIS_PORT
          value: "6379"
        - name: CACHE_DRIVER
          value: redis
        - name: QUEUE_CONNECTION
          value: redis
        - name: SESSION_DRIVER
          value: redis
        - name: HASHIDS_SALT
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: HASHIDS_SALT
        - name: HASHIDS_LENGTH
          value: "8"
        - name: MAIL_MAILER
          value: smtp
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: MAIL_HOST
        - name: MAIL_PORT
          value: "587"
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: MAIL_USERNAME
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: MAIL_PASSWORD
        - name: MAIL_ENCRYPTION
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: MAIL_ENCRYPTION
        - name: MAIL_FROM_ADDRESS
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: MAIL_FROM_ADDRESS
        - name: MAIL_FROM_NAME
          value: "Pterodactyl Panel"
        - name: MAIL_DRIVER
          value: smtp
        - name: MAIL_EHLO_DOMAIN
          valueFrom:
            secretKeyRef:
              name: pterodactyl-panel-secrets
              key: MAIL_EHLO_DOMAIN
        - name: APP_SERVICE_AUTHOR
          value: "Pterodactyl Panel"
        - name: PTERODACTYL_TELEMETRY_ENABLED
          value: "false"
        - name: SESSION_SECURE_COOKIE
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /data
      volumes:
      - name: config
        hostPath:
          path: /lxc-configs/pterodactyl-panel-config # This path contains the same files on all nodes 
          type: DirectoryOrCreate
