apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress-route.yaml

generators:
  - secret-generator.yaml

replacements:
# Ingress Route
  - source:
      kind: Secret
      name: pterodactyl-panel-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: pterodactyl-panel
        fieldPaths:
          - spec.routes.0.match

# Certificates
  - source:
      kind: Secret
      name: pterodactyl-panel-secrets
      fieldPath: stringData.APP_DOMAIN
    targets:
      - select:
          kind: Certificate
          name: pterodactyl-panel-cert
        fieldPaths:
          - spec.dnsNames.0