apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

generators:
  - secret-generator.yaml

replacements:
  - source:
      kind: Secret
      name: pterodactyl-panel-secrets
      fieldPath: stringData.APP_DOMAIN
    targets:
      - select:
          kind: Ingress
          name: pterodactyl-panel
        fieldPaths:
          - spec.rules.0.host
