apiVersion: apps/v1
kind: Deployment
metadata:
  name: accomplice-v2
  namespace: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accomplice-v2
  template:
    metadata:
      labels:
        app: accomplice-v2

    spec:
      containers:
      - name: accomplice-v2
        image: gotkrypto/accomplice-v2:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: accomplice-secrets
              key: DISCORD_TOKEN
        - name: DISCORD_DISPLAY_NAME
          value: "Accomplice"
        - name: DISCORD_ACTIVITY_REFRESH_INTERVAL
          value: "60"
        - name: DISCORD_BOT_ADMIN_SNOWFLAKE
          value: "707022657354203180"
        - name: REDIS_ENABLED
          value: "false"
        - name: REDIS_URL
          secretKeyRef:
              name: accomplice-secrets
              key: REDIS_URL
        - name: REDIS_PREFIX
          value: "accomplice_v2_prod"
        - name: DB_PROD_DIALECT
          value: "mariadb"
        - name: DB_PROD_HOST
          secretKeyRef:
              name: accomplice-secrets
              key: MARIADB_HOST_PROD
        - name: DB_PROD_PORT
          value: "3306"
        - name: DB_PROD_USERNAME
          secretKeyRef:
              name: accomplice-secrets
              key: MARIADB_USERNAME_PROD
        - name: DB_PROD_PASSWORD
          secretKeyRef:
              name: accomplice-secrets
              key: MARIADB_PASSWORD_PROD
        - name: DB_PROD_DATABASE
          secretKeyRef:
              name: accomplice-secrets
              key: MARIADB_DATABASE_PROD
        - name: DB_DEV_DIALECT
          value: "mariadb"
        - name: DB_DEV_HOST
          secretKeyRef:
              name: accomplice-secrets
              key: MARIADB_HOST_DEV
        - name: DB_DEV_PORT
          value: "3306"
        - name: DB_DEV_USERNAME
          secretKeyRef:
              name: accomplice-secrets
              key: MARIADB_USERNAME_DEV
        - name: DB_DEV_PASSWORD
          secretKeyRef:
              name: accomplice-secrets
              key: MARIADB_PASSWORD_DEV
        - name: DB_DEV_DATABASE
          secretKeyRef:
              name: accomplice-secrets
              key: MARIADB_DATABASE_DEV