# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: accomplice-v2
#   namespace: discord
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: accomplice-v2
#   template:
#     metadata:
#       labels:
#         app: accomplice-v2

#     spec:
#       containers:
#       - name: accomplice-v2
#         image: gotkrypto/accomplice-v2:latest
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "250m"
#           limits:
#             memory: "256Mi"
#             cpu: "1000m"
#         env:
#         - name: NODE_ENV
#           value: "${ACCOMPLICE_V2_ENV}"
#         - name: DB_ENV
#           value: "${ACCOMPLICE_V2_ENV}"
#         - name: LOG_LEVEL
#           value: "${ACCOMPLICE_V2_LOG_LEVEL}"
#         - name: DISCORD_TOKEN
#           value: "${SECRET_ACCOMPLICE_V2_TOKEN}"
#         - name: DISCORD_DISPLAY_NAME
#           value: "${ACCOMPLICE_V2_DISPLAY_NAME}"
#         - name: DISCORD_ACTIVITY_REFRESH_INTERVAL
#           value: "60"
#         - name: DISCORD_BOT_ADMIN_SNOWFLAKE
#           value: "707022657354203180"
#         - name: REDIS_ENABLED
#           value: "false"
#         - name: REDIS_URL
#           value: "${SECRET_ACCOMPLICE_V2_REDIS_URL}"
#         - name: REDIS_PREFIX
#           value: "${ACCOMPLICE_V2_REDIS_PREFIX}"
#         - name: DB_PROD_DIALECT
#           value: "mariadb"
#         - name: DB_PROD_HOST
#           value: "${ACCOMPLICE_V2_MARIADB_HOST}"
#         - name: DB_PROD_PORT
#           value: "3306"
#         - name: DB_PROD_USERNAME
#           value: "${SECRET_ACCOMPLICE_V2_MARIADB_PROD_USERNAME}"
#         - name: DB_PROD_PASSWORD
#           value: "${SECRET_ACCOMPLICE_V2_MARIADB_PROD_PASSWORD}"
#         - name: DB_PROD_DATABASE
#           value: "${SECRET_ACCOMPLICE_V2_MARIADB_PROD_DATABASE}"
#         - name: DB_DEV_DIALECT
#           value: "mariadb"
#         - name: DB_DEV_HOST
#           value: "${ACCOMPLICE_V2_MARIADB_HOST}"
#         - name: DB_DEV_PORT
#           value: "3306"
#         - name: DB_DEV_USERNAME
#           value: "${SECRET_ACCOMPLICE_V2_MARIADB_DEV_USERNAME}"
#         - name: DB_DEV_PASSWORD
#           value: "${SECRET_ACCOMPLICE_V2_MARIADB_DEV_PASSWORD}"
#         - name: DB_DEV_DATABASE
#           value: "${SECRET_ACCOMPLICE_V2_MARIADB_DEV_DATABASE}"
