apiVersion: apps/v1
kind: Deployment
metadata:
  name: recyclarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recyclarr
  template:
    metadata:
      labels:
        app: recyclarr

    spec:
      containers:
      - name: recyclarr
        # https://github.com/recyclarr/recyclarr/pkgs/container/recyclarr
        image: ghcr.io/recyclarr/recyclarr:6.0.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
        - name: recyclarr-config
          mountPath: /config
      volumes:
      - name: recyclarr-config
        hostPath:
          path: /lxc-configs/recyclarr-config # This path contains the same files on all nodes 
          type: DirectoryOrCreate