apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads-sabnzbd-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: sonarr-downloads-sabnzbd-pv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: sonarr-media-pv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: web
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: sonarr-config-pv
  resources:
    requests:
      storage: 1Ti