apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: web
spec:
  replicas: 0
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea

    spec:
      containers:
      - name: gitea
        # https://hub.docker.com/r/gitea/gitea/tags?page=1
        image: gitea/gitea:1.21.7
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
          - containerPort: 3000
          - containerPort: 222
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: DISABLE_REGISTRATION
          value: "true"
        - name: GITEA__database__DB_TYPE
          value: "mysql"
        - name: GITEA__database__HOST
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: DB_HOST
        - name: GITEA__database__NAME
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: DB_DATABASE
        - name: GITEA__database__USER
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: DB_USERNAME
        - name: GITEA__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: DB_PASSWORD
        volumeMounts:
          - name: gitea-data
            mountPath: /data
      volumes:
      - name: gitea-data
        nfs:
          server: "10.100.0.1"
          path: /mnt/tank/gitea