apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: &appname gitea
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: ingress-route-match
      priority: 10
      services:
        - name: *appname
          port: 80
      middlewares:
        - name: https-only
  tls:
    secretName: gitea-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: gitea-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: ingress-route-match
      priority: 10
      services:
        - name: gitea
          port: 80
      middlewares:
        - name: https-only
