apiVersion: v1
kind: Secret
metadata:
    name: gitea-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:gFtZ6XCsWDgl4mPQ018bdMM2uF48kc8S,iv:UnLWrw+uNMY0Tc98/fjcZwBi+V/0PvTn4cnrsziJiak=,tag:b8efSzM0g65c6LidsiA0ww==,type:str]
    INGRESS_ROUTE_AUTHENTIK: ENC[AES256_GCM,data:D+Bqi4+JEq+PG4KVPeBIRvWI51bsbkU/qDj/oz7VzD3UsIyOzlyqeKfBcrhAmVQeXA9nuc2tsIk3v+aPRKU+bOJG,iv:ofJQeglvzpk0BTtM9+8YTGVThUNcn+ky7XpRExxKCk0=,tag:3dgUltZu7HUWHJNi/pFOvw==,type:str]
    GITEA_URI: ENC[AES256_GCM,data:4iMv7/OKUxQ9o7bbbu958Q==,iv:SHQyEb1wMzrCTrq4H1BTCC0dQF5Ix2CdodobHFEdMs0=,tag:RS1r4h06dOL2CZHrKlkQrg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:P7bWImVlXQ9l,iv:9FO6oe2K83v1KBI/IJjkki/1SV9VB7xWYsKlf2nNDsE=,tag:kCassRgYM5zyLy46dOTdIQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:yeGz+l8=,iv:kkBxnVZ5/IrJj41/h0eVAjWGN2OXbkxsOJoBpfRtpmg=,tag:jB7WkyUQiaLi14IC2l9Auw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:LFV/06E=,iv:UyM6Uxvthsoull7kexiuNaNgAoqYmSxldZYglc2kLRA=,tag:/AR2wBpW3IVBDCnYP09K5Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:NRkCqS/ySDd0URiikTelnMk57w==,iv:YsWJmdHLBV6dwKRFPkE4SeSfngDPqHqiYuXO48rclF0=,tag:9eDUMgvq5K+EfEjMAqks6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-02T07:34:29Z"
    mac: ENC[AES256_GCM,data:RNQbJGvoGu6PvldIBas4agjjl9f7YNaksKNnQyknIZA19WULc+E21LMSIjCWkOJrHB+zwSbV9FNIZHps1Qd0trySYSggdXelKnfTalOebMHrV0iucDocNbXFeK3WxdYxNxH/9e+OCgTzu2IzUKiWK9krWMa8KPts1ZYPLb4lNeg=,iv:rnNzo3J80cO9kmHpsLR14h8SyLWUOGzjZilGakk0iCY=,tag:L3ct2wAdcpt2qJESWJU8UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
