apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: umami-mwl
spec:
  entryPoints:
    - web
  routes:
    - match: ingress-route-match
      kind: Rule
      services:
        - name: umami
          port: 80

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: umami-alt
spec:
  entryPoints:
    - web
  routes:
    - match: ingress-route-match-alt
      kind: Rule
      services:
        - name: umami
          port: 80
