apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress-route.yaml

generators:
  - secret-generator.yaml

replacements:
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.IMAGE
    targets:
      - select:
          kind: Deployment
          name: umami
        fieldPaths:
          - spec.template.spec.containers.0.image
# Ingress Route
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: umami-mwl
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH_ALT
    targets:
      - select:
          kind: IngressRoute
          name: umami-alt
        fieldPaths:
          - spec.routes.0.match

  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: umami-http-mwl
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: umami-http-alt
        fieldPaths:
          - spec.routes.0.match

# Certificates
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.UMAMI_URL_MWL
    targets:
      - select:
          kind: Certificate
          name: umami-cert-mwl
        fieldPaths:
          - spec.dnsNames.0
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.UMAMI_URL_LONG_MWL
    targets:
      - select:
          kind: Certificate
          name: umami-cert-mwl
        fieldPaths:
          - spec.dnsNames.1

  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.UMAMI_URL_GKRYPT
    targets:
      - select:
          kind: Certificate
          name: umami-cert-alt
        fieldPaths:
          - spec.dnsNames.0
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.UMAMI_URL_MFOX
    targets:
      - select:
          kind: Certificate
          name: umami-cert-alt
        fieldPaths:
          - spec.dnsNames.1
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.UMAMI_URL_CRUST
    targets:
      - select:
          kind: Certificate
          name: umami-cert-alt
        fieldPaths:
          - spec.dnsNames.2
  - source:
      kind: Secret
      name: umami-secrets
      fieldPath: stringData.UMAMI_URI_LONG_CRUST
    targets:
      - select:
          kind: Certificate
          name: umami-cert-alt
        fieldPaths:
          - spec.dnsNames.3