apiVersion: v1
kind: Secret
metadata:
    name: umami-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:I6vy9RJc+ZynuN56INBrg4cZcyg9hs3PnCdLyI5YWb8GIZZPGg42spqSmSs0bhkuytpgEw==,iv:oSyWvmsYNlwVKz2XbPATQevOiKytAXPXN279NRqO1X0=,tag:/ckKtQzKTq72H8oC2geJ3w==,type:str]
    INGRESS_ROUTE_MATCH_ALT: ENC[AES256_GCM,data:/okrs+ZRrsfYLfANyMzBgvVNiY23w0y0xRoVGmWIbMfGk/qVVCkUjtZtdQ2vlXtKEzLf+lqZTFOM9DFEyZrqwtzSCgBUpxoLgx5v2M0Li+QsbKT8M/XNomX8qPwbrIlE083zF6iFqDI=,iv:f2o9fgmydZpZVrwB7cC5NRsuMhl1907yOXnhsX7Bzbo=,tag:/TYaf1gZT6AgHAtj+VbV/Q==,type:str]
    UMAMI_URL_GKRYPT: ENC[AES256_GCM,data:MX16FwibmbUBQzR+,iv:8cDYHS12LFEXrMjqGmtqLtMwhzzSEStZdxWImkWg2H4=,tag:sqpmaB/zwBkHT/KxKjHlXA==,type:str]
    UMAMI_URL_MFOX: ENC[AES256_GCM,data:XWJgiBnkGM5eH/Afh6k=,iv:P9P1I/Wr77au16BETWWRWpIX+eOwQh0uazF0LDdV5WE=,tag:ua3c+ewbvZZHOHiNqBgRYw==,type:str]
    UMAMI_URL_MWL: ENC[AES256_GCM,data:3jUCuBKaM7a0VR2COpI=,iv:oCD+y2bvIpC6kVGa95ytvRXfkjZOzJjtE4LPhZ9y8Vc=,tag:kN20A6NlMxtqOZaoU+RP5A==,type:str]
    UMAMI_URL_CRUST: ENC[AES256_GCM,data:LUvzQ0U0hDmZCek4/jVe,iv:x3PTUHiKBCQQmdFvocRPQqFAim8092N9fMPJEXweO7s=,tag:J8PNHyGPnwkSePtkiwhLYg==,type:str]
    UMAMI_URI_LONG_CRUST: ENC[AES256_GCM,data:oYycqJB4THrZgihwmUFfS5bzPA==,iv:iyaqHR201BC48QwMuVMD1R6PYBiTxxTvIgvfCzz5h/8=,tag:+3aN5yc9fXYR9D+pxMjivw==,type:str]
    UMAMI_URI_LONG_MWL: ENC[AES256_GCM,data:sy+YK/B3pwFPw8rAkASQBpk3,iv:u2ezaz8gIV2H/Ux/ffZcJ2zuJtLe3EbJFbthP4fjdNo=,tag:IB3ORcubEa5P2+JyWmndSQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:yJWOVYiPIOD1ot8bY7CzqjGV+whkN+hamKoO3Mfo636zbbt+Pwr+t13tLVxIrSXl2Y4UZ1DSeQ==,iv:QcnBRVWCmx02SG/xYpajsBgecgq3MOEF88nmeWdliww=,tag:3YO9UuVce7RPRHntThcaww==,type:str]
    HASH_SALT: ENC[AES256_GCM,data:3oY8zoqXyMhHQLfGXAvki+bAziXhrQZ0QRHHktSYFGswMtSn,iv:t51l/j9cQaNwZkSV9vOGODE9ckHjbDFDLv5ft1r7sWo=,tag:mfDWajPILl3niHd/QBmMqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-11T23:38:15Z"
    mac: ENC[AES256_GCM,data:N9KwCCteLuOCPQ6kULOgsrc+Wi5rVAcgEmd2BeLAsC1bkODrbIVDzUBSUJuQWXdiUxOx6iBh4tQ3DYK4/kcoYCYECB/3Mu5xm5h7sP/Itj7M+pGP/Q5P+lQPEo0qvni1N8m0a25BtnBUXQ0m4EmBA9P/rT9Fe+XoQfMXohA+Uqc=,iv:/XadnD+ROhKUqGyiprIOGya1yk4IO6Y799oPUBqeQMA=,tag:gijCPe8sfEIkv+1jukyDXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
