apiVersion: v1
kind: Secret
metadata:
    name: umami-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:oSnKsm5vVddFHmvxb5wYyrpVgw2sHBIWMIrCg/nef8LHzMrRkOf95inWHALozLOfalwIIg==,iv:rR0lmIkc+eLjSXT/HsF1E3EPJMxsfLkCNlMztNszz2k=,tag:R7+1tYj2YMbW5BllvJLLLQ==,type:str]
    INGRESS_ROUTE_MATCH_ALT: ENC[AES256_GCM,data:wmQJ1R0PtV2f+dn041NpG1VseDj7OqTX08nwtStzreIznq7l5z21US++n1700IGr7RChFcU9LXLqQqb5lfFGq4rp5wH20I0g+TrOYwHL3IRreHoozKqv3/k201/1Hr6Q6b4XuyiOLqQ=,iv:kj+GjJLQrEwTUOcn4pas3kgaC1/mjEo+U8YYhg84goA=,tag:GNnRKFTUhUKay45pvM1qUA==,type:str]
    UMAMI_URL_GKRYPT: ENC[AES256_GCM,data:MX16FwibmbUBQzR+,iv:8cDYHS12LFEXrMjqGmtqLtMwhzzSEStZdxWImkWg2H4=,tag:sqpmaB/zwBkHT/KxKjHlXA==,type:str]
    UMAMI_URL_MFOX: ENC[AES256_GCM,data:XWJgiBnkGM5eH/Afh6k=,iv:P9P1I/Wr77au16BETWWRWpIX+eOwQh0uazF0LDdV5WE=,tag:ua3c+ewbvZZHOHiNqBgRYw==,type:str]
    UMAMI_URL_MWL: ENC[AES256_GCM,data:3jUCuBKaM7a0VR2COpI=,iv:oCD+y2bvIpC6kVGa95ytvRXfkjZOzJjtE4LPhZ9y8Vc=,tag:kN20A6NlMxtqOZaoU+RP5A==,type:str]
    UMAMI_URL_CRUST: ENC[AES256_GCM,data:LUvzQ0U0hDmZCek4/jVe,iv:x3PTUHiKBCQQmdFvocRPQqFAim8092N9fMPJEXweO7s=,tag:J8PNHyGPnwkSePtkiwhLYg==,type:str]
    UMAMI_URL_LONG_CRUST: ENC[AES256_GCM,data:RVczSqQdl/DMTsnFkvxtkvKYPw==,iv:L0nPAX0dITb06wkuKH33UuCbQ6jHzRI2kPPldHCDYKQ=,tag:Md8xqCpXnJWIiN7ea8vrHA==,type:str]
    UMAMI_URL_LONG_MWL: ENC[AES256_GCM,data:NJaCURxrWx0EgraFIXldEKF7,iv:d71S5fv8W604FUE3jIhj3GlrRtEa8sfuoBXGKrylWGc=,tag:Cpk48PPil7w42QCOel5ULg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vba/8PA9QPxj/RvpwBFjx2s1nlr9Ix8snmO3cyyum6xFKqXVAhaMTaKqpjTdZ10hkJ22nucbBQ==,iv:Q25S07VjNAhNOM2vNv7EqLT7VSi7QtNHblnq66cl7Co=,tag:VWKMB0+99u2D9EXouwxulQ==,type:str]
    HASH_SALT: ENC[AES256_GCM,data:3oY8zoqXyMhHQLfGXAvki+bAziXhrQZ0QRHHktSYFGswMtSn,iv:t51l/j9cQaNwZkSV9vOGODE9ckHjbDFDLv5ft1r7sWo=,tag:mfDWajPILl3niHd/QBmMqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T04:36:53Z"
    mac: ENC[AES256_GCM,data:fJnt+Jid7D7oVWUlA/XJW7W13paU/oX1pqsT0iLfu4yxGywqBQa6TA2bVBjikmcvD0oetyKDso4DqbePN6E7rKEMIFjYpewZfg9+20W1WK4SKaroSZIGaOaAOY8LMA9ieb012xdFbUm+Rbvk2pXYRItQj34QiYyJrCnS1xCbnqc=,iv:4+Jiv7D3zcUNKCOSjlJWh+qDLn914rNMe3LHwxhkrhs=,tag:vgfk9gvm0+9/8NOgNikH0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
