apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - csi-driver.yaml
  - controller.yaml
  - node.yaml
  - storage-class.yaml
  - media-pvcs.yaml
  - secrets.sops.yaml
