namespace: kube-system

driver:
  name: nfs.csi.k8s.io

controller:
  extraVolumes:
    - name: nfs-kerberos-secrets
      secret:
        secretName: nfs-kerberos-secrets
        items:
        - key: krb5.conf
          path: krb5.conf
        - key: nfs.keytab
          path: nfs.keytab
  extraVolumeMounts:
    - name: nfs-kerberos-secrets
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
      readOnly: true
    - name: nfs-kerberos-secrets
      mountPath: /etc/krb5.keytab
      subPath: nfs.keytab
      readOnly: true

node:
  extraVolumes:
    - name: nfs-kerberos-secrets
      secret:
        secretName: nfs-kerberos-secrets
        items:
        - key: krb5.conf
          path: krb5.conf
        - key: nfs.keytab
          path: nfs.keytab
  extraVolumeMounts:
    - name: nfs-kerberos-secrets
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
      readOnly: true
    - name: nfs-kerberos-secrets
      mountPath: /etc/krb5.keytab
      subPath: nfs.keytab
      readOnly: true