apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfox
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfox
  template:
    metadata:
      labels:
        app: mfox

    spec:
      containers:
      - name: mfox
        image: replaced-by-kustomize
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "4000m"
        ports:
          - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: ghcr-login-secret
