apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml

generators:
  - secret-generator.yaml

replacements:
  - source:
      kind: Secret
      name: mfox-secrets
      fieldPath: stringData.IMAGE
    targets:
      - select:
          kind: Deployment
          name: mfox
        fieldPaths:
          - spec.template.spec.containers.0.image
# Ingress Route
  - source:
      kind: Secret
      name: mfox-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: mfox
        fieldPaths:
          - spec.routes.0.match