apiVersion: v1
kind: Secret
metadata:
    name: mfox-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:RBnBKlCVfHZ9qZ10c+9/5GTrvVVXy6y4JKHjiAOW6f4ugJ9ZVvhjdY/nrzX7Xke6,iv:GJD6GdQ1KYNVYTZBNUT1qHiiFiPJeHDJyGT72ZiDzEo=,tag:OP5pfI00JjlxgTQa5pTAgA==,type:str]
    MFOX_URI: ENC[AES256_GCM,data:7gvsshqx0RVqhNWy,iv:atPGmLkNVsf3k3lvC3V2MMsZGpc2HbOKe1Yph0OPBaU=,tag:4L73r2VNT1Dd6eFHVDO5yw==,type:str]
    MFOX_URI_WWW: ENC[AES256_GCM,data:yAJ9B8Cd0+qKdaKnu3gU7A==,iv:Xf5Cme/Aj9SArNyi0g63rqicLigSSNl7EeEE8LLG+Qc=,tag:S/y1EYq0QfjBzC5aRMxuTw==,type:str]
    NEXT_PUBLIC_GA_MEASUREMENT_ID: ENC[AES256_GCM,data:7AmjV4AXwLBPdWPG,iv:MNdXtGWbZcsh3drp+gQZpnWYOoUe7PIxuc7FAgpQPQs=,tag:3HZ2rse+AAOS1PetriYncw==,type:str]
    IMAGE: ENC[AES256_GCM,data:H6HBW0knorvj6h41EqCE25y7s9ICMw5mPO7F0T0LyWKT+u/soO4sWA==,iv:mkoZlGKcsy+izdD5weD9sz3tKMOuMG6ctV4aPF4oQNU=,tag:9a2zRROxRE8h0e9Uz4Z0gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T23:33:48Z"
    mac: ENC[AES256_GCM,data:nsgbr/qwZRIwwzlFwHawcKsoAaX2HYqbqCqnuK2e1zLYMhMrCR4vnyQqJubDV2gdHKWIeHTNv3PZulTJm0Gi8ZSs50A96RPtbBfL8XSzHmbIi/EMfXA5Tr9YWGxEvng4aFK1lwuWxIcNjPnD6WrBfChEqkXTlDL1tg1ePCkoQ24=,iv:DRrgNJoVBSRBBqRfwlAF6nOo362sofKnXz0LPTQwgYo=,tag:iov6zrKC1QfvQtzrH05WuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
