apiVersion: v1
kind: Secret
metadata:
    name: mfox-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:RBnBKlCVfHZ9qZ10c+9/5GTrvVVXy6y4JKHjiAOW6f4ugJ9ZVvhjdY/nrzX7Xke6,iv:GJD6GdQ1KYNVYTZBNUT1qHiiFiPJeHDJyGT72ZiDzEo=,tag:OP5pfI00JjlxgTQa5pTAgA==,type:str]
    MFOX_URI: ENC[AES256_GCM,data:7gvsshqx0RVqhNWy,iv:atPGmLkNVsf3k3lvC3V2MMsZGpc2HbOKe1Yph0OPBaU=,tag:4L73r2VNT1Dd6eFHVDO5yw==,type:str]
    MFOX_URI_WWW: ENC[AES256_GCM,data:yAJ9B8Cd0+qKdaKnu3gU7A==,iv:Xf5Cme/Aj9SArNyi0g63rqicLigSSNl7EeEE8LLG+Qc=,tag:S/y1EYq0QfjBzC5aRMxuTw==,type:str]
    NEXT_PUBLIC_GA_MEASUREMENT_ID: ENC[AES256_GCM,data:7AmjV4AXwLBPdWPG,iv:MNdXtGWbZcsh3drp+gQZpnWYOoUe7PIxuc7FAgpQPQs=,tag:3HZ2rse+AAOS1PetriYncw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T05:47:49Z"
    mac: ENC[AES256_GCM,data:jIvwBAe1JXBOIpM5vgsHeVG5itihcWGI96TBHC4IPX/mVC2thgf2BmINp3w5LTZUx0lD/mV4XDd3Il0+MOH5GZfIfXAcFipAWnkkP9fpNx/ha8xapvbb1DpUzQJ+JJZdsIpqDGd4GjZhKRkebrG6ATkpGNkVmaA18ELbvElbUkY=,iv:I2IrBH6hF/gnrLadUc1lDv+9bt7hCmYQ6nCjvQNEmvo=,tag:MVuOh0RihXy6MpEPizxexg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
