apiVersion: v1
kind: Secret
metadata:
    name: mfox-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:2Wkj5Ya/pVdDkMuA3c0pl+Tqk2hOHzopa5OVdNsuOJ3cnmDF7xRSdBQNuOzXivXYyrqbrdEXZ9c+KprrkuWAAGIbJsgkyQ/PVvZRgcRjWGyPF21tUZSAVva1dhtQ6UQVvaS8pD9PYTsQkB4xn60=,iv:mFtxDoR3b+szHl/TL5vp2/PAapJ/cFOq0Y2CQWGIt+w=,tag:B+L7lXgfBZgTtBKHrlcaUw==,type:str]
    IMAGE: ENC[AES256_GCM,data:PHDVzGoOCRrgY9dvFUENENzca7v2AIowy0bwmT+ky7ScSEnJxNnaFg==,iv:ixDajwX5k2qiXxmS3564LU80UJpSossb7kgwFeg9CWw=,tag:wdqymeIxvW9KsVvzdp1LjQ==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T02:52:40Z"
    mac: ENC[AES256_GCM,data:dzK005wPaHrCNcQHgKDUE7Z41AcYDO6cZXT2lXhiVsBZ82uFoFJdzWFJFYmQzSq44BE8He1oIzqLJhI4umg3NoFjIlBt0oClH4QIJ0d+wgPh9U3ESE9KkXQ2TE0hQWsRmxG02OyCowHrv3kDbUJE33gXbgSy9Xs8nXzCkVcEK2E=,iv:904v7CfSbJO5EA9hF46OCQ0irbSiIt4oHTQ7/1y6awA=,tag:z/Ca1iEOtQJU3PZWbQjBVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
