apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  - ingress-route.yaml

generators:
  - secret-generator.yaml

replacements:
  - source:
      kind: Secret
      name: sonarr-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: sonarr
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: Secret
      name: sonarr-secrets
      fieldPath: stringData.INGRESS_ROUTE_AUTHENTIK
    targets:
      - select:
          kind: IngressRoute
          name: sonarr-authentik
        fieldPaths:
          - spec.routes.0.match
# Certificates
  - source:
      kind: Secret
      name: sonarr-secrets
      fieldPath: stringData.PUBLIC_URI
    targets:
      - select:
          kind: Certificate
          name: sonarr-cert
        fieldPaths:
          - spec.dnsNames.0