apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
type: Opaque
stringData:
    PUBLIC_URI: ENC[AES256_GCM,data:3FzwUaVcsdbSdOwzIarG079Pc7s=,iv:Hw49MdBwV3kbYwkk+iDChItnVuVpbIJHqVIwNdz3dbw=,tag:i3uTMJBIVhhrY4MkrQXZeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T09:25:24Z"
    mac: ENC[AES256_GCM,data:HExIMbi47vcka8cRfqBRg0quBT2Wp5SEbVkKb2BtcdvYp9RMvYU0xI/Y8QsVk2boW2Efx2a5vOz7NeRnLjLJJjYFnoKNR0OONRDuIONqI8Cw3KOwovLJs5Gjiox53IgQkF4nDqiPiBblCqivaP9CmYt4mm/pYpw5vEhWHBsJrK4=,iv:RB/qsI2HyfIs/Q+bv0ozZBoSamY4VKyeOAM/1LwfxS0=,tag:bpLSUj5Yass69Be/AM5TJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
