apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
type: Opaque
stringData:
    PUBLIC_URI: ENC[AES256_GCM,data:3FzwUaVcsdbSdOwzIarG079Pc7s=,iv:Hw49MdBwV3kbYwkk+iDChItnVuVpbIJHqVIwNdz3dbw=,tag:i3uTMJBIVhhrY4MkrQXZeg==,type:str]
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:y2+fymwYe+Wg6/nCs9nlEu0r4ak8x9d3DSQZwg==,iv:gzKjNxpmFPmRtO1FLh4cfBvoJPFAn6T/TaBsZuz5EbY=,tag:jNpWmF5J/li9vZ9lycMcvg==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T02:21:22Z"
    mac: ENC[AES256_GCM,data:oWWMCK4x1t+ZWVux6FeijfnVhy3BOwQK0O46rL5odtZfLy7uXgeaF+1yrIsqVPzcpfWpbYMdOEFIDKwz0K4BqG7ohBgr702DUIEmwDJqOspH16CImNKbudK3HZW9ZSvFfGHcIl5bKtm6Qjs3j0lXsOaRoXedFMfVNKG21ExnAP8=,iv:duUjH5m6algJGV0PFKNMPERuqeMFx9nxpBEHflBC+cE=,tag:cE6ND+9/mbezj9e6AYh5ww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
