apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-downloads-sabnzbd-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-downloads-sabnzbd
    volumeAttributes:
      source: "//10.100.0.1/mnt/ssd/services/test"
    nodeStageSecretRef:
      name: smb-creds
      namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-downloads-sabnzbd-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: smb-downloads-sabnzbd-pv
  resources:
    requests:
      storage: 1Ti
