apiVersion: apps/v1
kind: Deployment
metadata:
  name: filerun
  namespace: web
spec:
  replicas: 0
  selector:
    matchLabels:
      app: filerun
  template:
    metadata:
      labels:
        app: filerun

    spec:
      containers:
      - name: filerun
        image: filerun/filerun:8.1
        # securityContext:
        #   runAsNonRoot: true
        #   runAsUser: 33
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "6Gi"
            cpu: "6000m"
        ports:
          - containerPort: 80
        env:
        - name: FR_DB_HOST
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: FR_DB_HOST
        - name: FR_DB_PORT
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: FR_DB_PORT
        - name: FR_DB_NAME
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: FR_DB_NAME
        - name: FR_DB_USER
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: FR_DB_USER
        - name: FR_DB_PASS
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: FR_DB_PASS
        - name: APACHE_RUN_USER
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: APACHE_RUN_USER
        - name: APACHE_RUN_USER_ID
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: APACHE_RUN_USER_ID
        - name: APACHE_RUN_GROUP
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: APACHE_RUN_GROUP
        - name: APACHE_RUN_GROUP_ID
          valueFrom:
            secretKeyRef:
              name: filerun-secrets
              key: APACHE_RUN_GROUP_ID
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
        - name: filerun-config
          mountPath: /var/www/html
        - name: nas
          mountPath: /user-files
        - name: plex
          mountPath: /user-files/maxwlang/Plex
      volumes:
      - name: filerun-config
        hostPath:
          path: /lxc-configs/filerun-config # This path contains the same files on all nodes 
          type: DirectoryOrCreate
      - name: nas
        nfs:
          server: "10.100.0.1"
          path: /mnt/tank/storage/filerun
      - name: plex
        nfs:
          server: "10.100.0.1"
          path: /mnt/tank/kubernetes/plex/media
      imagePullSecrets:
      - name: ghcr-login-secret
