apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbinger
  namespace: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbinger
  template:
    metadata:
      labels:
        app: harbinger

    spec:
      containers:
      - name: harbinger
        image: ghcr.io/maxwlang/harbinger:v1.1.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "2000m"
        env:
        - name: CURRENT_CONGRESS
          value: "119th"
        - name: DISCORD_WEBHOOK_FRIENDS
          valueFrom:
            secretKeyRef:
              name: harbinger-secrets
              key: DISCORD_WEBHOOK_FRIENDS
        volumeMounts:
        - name: harbinger-data
          mountPath: /data
      volumes:
      - name: harbinger-data
        hostPath:
          path: /lxc-configs/harbinger-data # This path contains the same files on all nodes 
          type: DirectoryOrCreate
