apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrisitian
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrisitian
  template:
    metadata:
      labels:
        app: chrisitian

    spec:
      containers:
      - name: chrisitian
        image: ghcr.io/maxwlang/chrisitian:v1.1.0
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "4000m"
        ports:
          - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_GA_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: chrisitian-secrets
              key: NEXT_PUBLIC_GA_MEASUREMENT_ID
        - name: NEXT_PRIVATE_MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: chrisitian-secrets
              key: NEXT_PRIVATE_MARIADB_HOST
        - name: NEXT_PRIVATE_MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: chrisitian-secrets
              key: NEXT_PRIVATE_MARIADB_USER
        - name: NEXT_PRIVATE_MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chrisitian-secrets
              key: NEXT_PRIVATE_MARIADB_PASSWORD
        - name: NEXT_PRIVATE_MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: chrisitian-secrets
              key: NEXT_PRIVATE_MARIADB_DATABASE
      imagePullSecrets:
      - name: ghcr-login-secret
