apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrisitian
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrisitian
  template:
    metadata:
      labels:
        app: chrisitian

    spec:
      containers:
      - name: chrisitian
        image: ghcr.io/maxwlang/chrisitian:v1.0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
          - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-login-secret