apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

generators:
  - secret-generator.yaml

replacements:
  - source:
      kind: Secret
      name: nginx-static-sites-secrets
      fieldPath: stringData.CHR_URI
    targets:
      - select:
          kind: Ingress
          name: nginx-static-sites
        fieldPaths:
          - spec.rules.0.host
  - source:
      kind: Secret
      name: nginx-static-sites-secrets
      fieldPath: stringData.CHR_URI_WWW
    targets:
      - select:
          kind: Ingress
          name: nginx-static-sites
        fieldPaths:
          - spec.rules.1.host
