apiVersion: v1
kind: Secret
metadata:
    name: itff-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:xvLiwMCg+sPk0oDGtT8X8tkDQXPEL4NgIa2DaPSHxBjmA944vXItinUgXu5gZ/L4x6/c0Hpgto4=,iv:cpveKvw8N4X2tbhFm11gpmu2XWj3Oo6jB1c/yoUEEVc=,tag:pjO3GQQ3KbxpO3h5aLEcpw==,type:str]
    IMAGE: ENC[AES256_GCM,data:Pc42pi94fBNeLIcGAEAzl6maAdeJ6gSM9P57vGPNRkZaSCYfiWY/iA==,iv:tgOZ9YCcVBSs+zaeCV4XoUQpqUny7sklDdbBlbJQpNU=,tag:HRsBCiqmxJbYWR7GsmSNxQ==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T03:01:26Z"
    mac: ENC[AES256_GCM,data:OoeYolK2ln1rNuxUz5PjDNvvI3oTcv0uVTWGPW4QOyz7QqLNvuvykvLmMkHmLjgXxH1m74b7utON6bY+mR1LS+FAAClSaZ+Ws3hmv4Dxz3Y01xvBTUYS92qCkuRhXmHArRFSXtpJDaZXlwBkcWsWggQp5TaA7oiHIbA80u66iMw=,iv:uU0PJwPKFJooOm7z5QAWEkPpKpCGjpWijgsMM86Z6fY=,tag:+WKwd8bA7EruIOQXGEFkmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
