apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-cert
spec:
  secretName: sabnzbd-cert
  dnsNames: 
    - overwritten-by-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod