apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads-sabnzbd-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: sabnzbd-downloads-sabnzbd-pv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: sabnzbd-media-pv
  resources:
    requests:
      storage: 1Ti