apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-vpn-media
spec:
  selector:
    app: sabnzbd-vpn-media
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
