apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbinger
spec:
  destination:
    namespace: discord
    server: https://kubernetes.default.svc
  project: discord
  source:
    repoURL: git@github.com:maxwlang/argocd-homelab.git
    path: apps/discord/harbinger
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
