apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: g4f-api
spec:
  destination:
    namespace: gpu
    server: https://kubernetes.default.svc
  project: gpu
  source:
    repoURL: git@github.com:maxwlang/argocd-homelab.git
    path: apps/gpu/g4f-api
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
