apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-middleware
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: media
  source:
    repoURL: git@github.com:maxwlang/argocd-homelab.git
    path: apps/media/middleware
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
