apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-persistent-volumes
spec:
  destination:
    namespace: system
    server: https://kubernetes.default.svc
  project: system
  source:
    repoURL: git@github.com:maxwlang/argocd-homelab.git
    path: apps/system/persistent-volumes
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
