apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filerun
spec:
  destination:
    namespace: web
    server: https://kubernetes.default.svc
  project: web
  source:
    repoURL: git@github.com:maxwlang/argocd-homelab.git
    path: apps/web/filerun
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
