apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: web
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GFfzybI4tdTKHiMpmAnBnmetNGmQwt+ar3+P0RDtQUn6DFcahYM3MyP4,iv:FDcHiTlYovboR2CvpXu42ngXB0n9xll9eGw53tuMtMY=,tag:S0D0V3RUH3kTPHHwU2wSww==,type:comment]
    #ENC[AES256_GCM,data:mBKyuuOmH8WQX7K/IjDK72ptFR0NNn4pFeyxmAOHVD16lZxg3QHm9aA6SllHg3G60A==,iv:/6g53r41KZLzSY6jcvZFL1cSakx0gFwBfse3Xe1vbsU=,tag:Fzvpv8qzuYcbv+beHrSpCQ==,type:comment]
    #
    #ENC[AES256_GCM,data:cv2iJZpZbPa6o/uQwuqUZHqkFmc=,iv:R71bGCElsB5GtTd0/vSZjUyOBOfErIGUf00BUNRyClg=,tag:EGRrDKzu+uB8TJLTLBA3Ug==,type:comment]
    #ENC[AES256_GCM,data:QWou2vLbYxJdSoZ7RJ6CxxdB2lPFuBTkYTol8tYmQz0Do0KCGDvlXEZtVTj8FfxP5w==,iv:ahZb5/9yqIxHPMw3mmN8IcpfgphEB1x8cOlrjPAhTuE=,tag:Res0EzJo2+Y/BQP4l7hVxA==,type:comment]
    #ENC[AES256_GCM,data:OnZbyBv4WUfQvkZBHNIsXXa/DXvhpnp1edq8l9IhorPInSEsOryP3Smf3t67qMun,iv:qG9izhjPBDi3OtD2K+dY6LXBedr3AH+G5enPtad1LA4=,tag:XhJMi8nUUYjW8js/yCoG/A==,type:comment]
    #ENC[AES256_GCM,data:hFQ5JmCt0o2EKDK6P0V4wzcB9Ajw8uy7i9URJKGG3g==,iv:+/O52rXURhzGfsay4I9uOE1gFskqg4jPC5DeRlkL7j0=,tag:lzvj46G4AqRn7S0vZIJ0tQ==,type:comment]
    #ENC[AES256_GCM,data:SFx3ePRzS45zkHLHkoiaNBsg+brsgnVd2KbzBg5Mc2sqWdsrGvysUMcC8r9NE6nimAsPG+s2kTCCvibGrC+bZcEHuks=,iv:UWhh2+46m+e0oUoch2+YRQ9+Ve+c1xTuBwvXwLOuAzk=,tag:7LO4cQhzkXe+UV5w3/T57Q==,type:comment]
    #ENC[AES256_GCM,data:Y5JRc83Wkv3BsiUbQq22gynnZbU=,iv:X10xTJ6DzxaVNBGc6zJ08IfLIWTdXbXAi52tID99HjA=,tag:rrU2tWsfLmZbtHM/2SCTyQ==,type:comment]
    #ENC[AES256_GCM,data:VLyNrxYGwyhy5VsAREV+vcdWhYwpasvqfzrmNgg5VBNzEwDhId1Jrj7cuEsHY14=,iv:wX5zhKY2aSvMuJngqfFR322sstc6lnaXtNxLuz34mkw=,tag:363cOush5fWodRH/FJq/EQ==,type:comment]
    #ENC[AES256_GCM,data:Veb5z4bIUBFMKkmWBJcG5hgIpX7NzklbZ9X9,iv:LGNHpzHJ4fqB8WAUmJ5LpEOEeaWBogi6CnN656dKfkg=,tag:J9RgXflmJxl15NDrChkoeA==,type:comment]
    #
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:uvaQQ2HysXpDr0TorPdstjV75RjAB0dl3m4=,iv:PWURl4P2Xrb6Bi678Q4rf7FiQ6fN3LrFPydAxrGjtCo=,tag:D+2rLDmNTxnI168hRnTSuA==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:e6GPdEvct7s89rGS,iv:U9PzFcxFyD8mw4tMVVjYw67xgDDzcwwii8fOSK13Wuw=,tag:V/CN1tNtrX0qv2+PNoufkQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:odQ4eA9Hoq2d7ZVdmz2hB/Cai+DI+w==,iv:cR9G+t0fsptfbgHbXu5nLKPjI6SyzeQ/E9jnMNYTYkQ=,tag:6JkvZihcLpGEWWzpDT++GA==,type:str]
    OAUTH2_PROXY_OIDC_ISSUER_URL: ENC[AES256_GCM,data:zRoTHRQCUVsKanwXz0AOZbFzFaENzeOzv0Tl4wH4halAo39ARVkq/iWliA==,iv:1v7aij4YSlF7AROGHXlFn7EYHU4sCPWTs3GJu+rV1Q0=,tag:nJAN/yIfbyCN9OYwL/G5kw==,type:str]
    #ENC[AES256_GCM,data:eK5WOAYG8aXMq2t1wqDJouFmq4L71adxmheWCcKC69KCv2JGbl6bVAwoFxzh+enKBpynRfiAy6Jo,iv:i5IPm7KSLLOD3/ksQ/7/TkSabEedCZ04hpWZAi+hWww=,tag:vnV/f6LXWgDo6Kt2lRjo7Q==,type:comment]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:bwWYiXmpBykNK+vAceapzKNpF44UgkXphL3g07+7A/eXcxLfTBkrftMqTPg=,iv:n/i7tFV0j/zvBTMLBZTilX8374q6rcfY2OlWnrAQjbg=,tag:lMRcworDJUR34m6QQWRlZg==,type:str]
    OAUTH2_PROXY_COOKIE_DOMAIN: ENC[AES256_GCM,data:+hjcBzLeEjWtC6tOCw==,iv:Y7ISkt4fP/nXYhOly/jaH4eAH6t1uKCYH3aKtQ6QESo=,tag:KvgV6ORqdfS+4ieg2VKZ1A==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aVlJTGI3TkN0eUJzUCtZ
            YWZ4YTk2UDBBVmpCSVJORTBmNUNMMXlWUDJZCkFyYnRBNE90WVh6N21pS2s1Ymx0
            Q3hlRUpGcW83VEFIMHVKNE5SbERPWmcKLS0tIE5wakRrQWxIYnNFVmtFcmV6K3Uv
            Y281OEJqd1V6bXRIdjdraDhUTGw4elEKlxZVp0DGl6qLGpN2fIvG2SGJyimjYQZi
            AS8DlNcF+VRp6OyxvM7h4zT3fJLxE3fB0HS+vCAatwZ1qQSxUq3GFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:37:46Z"
    mac: ENC[AES256_GCM,data:iQiv0dbws68/9E46x6eyO7q+NErcMfMc9P26W2B8PSzPQCHuYqs6zn+zk4lVfyU21pKyCpSXI6l62T4CqhR0UEJ5orSKE2niGbDsEa6xAlxeBjP9sZG9tJqqmziWvraGYAAzwT0UwZYch6AnqzNG3NgdgutYFy1R1UQM2CkNrJQ=,iv:QFomlL5Urh3kz6aocF7rTky39YdY7W4cR+gFm2HutT4=,tag:hLsls6lRmq7Sr0zAwl5Lzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
