apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: web
type: Opaque
stringData:
  # TODO: Encrypt with SOPS before committing
  # Run: sops --encrypt --in-place secrets.sops.yaml
  #
  # SETUP INSTRUCTIONS:
  # 1. In Keycloak, create a realm (e.g., "homelab")
  # 2. Create a client (e.g., "oauth2-proxy") with:
  #    - Client authentication: ON
  #    - Valid redirect URIs: http://oauth.example.com/oauth2/callback
  #    - Web origins: *
  # 3. Copy the client secret from Credentials tab
  # 4. Update the values below
  #
  INGRESS_ROUTE_MATCH: "Host(`oauth.example.com`)"
  OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
  OAUTH2_PROXY_CLIENT_SECRET: "changeme-client-secret"
  OAUTH2_PROXY_OIDC_ISSUER_URL: "http://keycloak.example.com/realms/homelab"
  # Generate with: openssl rand -base64 32 | tr -- '+/' '-_'
  OAUTH2_PROXY_COOKIE_SECRET: "changeme-cookie-secret-32-bytes"
  OAUTH2_PROXY_COOKIE_DOMAIN: ".example.com"
