apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: web
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GFfzybI4tdTKHiMpmAnBnmetNGmQwt+ar3+P0RDtQUn6DFcahYM3MyP4,iv:FDcHiTlYovboR2CvpXu42ngXB0n9xll9eGw53tuMtMY=,tag:S0D0V3RUH3kTPHHwU2wSww==,type:comment]
    #ENC[AES256_GCM,data:mBKyuuOmH8WQX7K/IjDK72ptFR0NNn4pFeyxmAOHVD16lZxg3QHm9aA6SllHg3G60A==,iv:/6g53r41KZLzSY6jcvZFL1cSakx0gFwBfse3Xe1vbsU=,tag:Fzvpv8qzuYcbv+beHrSpCQ==,type:comment]
    #
    #ENC[AES256_GCM,data:cv2iJZpZbPa6o/uQwuqUZHqkFmc=,iv:R71bGCElsB5GtTd0/vSZjUyOBOfErIGUf00BUNRyClg=,tag:EGRrDKzu+uB8TJLTLBA3Ug==,type:comment]
    #ENC[AES256_GCM,data:QWou2vLbYxJdSoZ7RJ6CxxdB2lPFuBTkYTol8tYmQz0Do0KCGDvlXEZtVTj8FfxP5w==,iv:ahZb5/9yqIxHPMw3mmN8IcpfgphEB1x8cOlrjPAhTuE=,tag:Res0EzJo2+Y/BQP4l7hVxA==,type:comment]
    #ENC[AES256_GCM,data:OnZbyBv4WUfQvkZBHNIsXXa/DXvhpnp1edq8l9IhorPInSEsOryP3Smf3t67qMun,iv:qG9izhjPBDi3OtD2K+dY6LXBedr3AH+G5enPtad1LA4=,tag:XhJMi8nUUYjW8js/yCoG/A==,type:comment]
    #ENC[AES256_GCM,data:hFQ5JmCt0o2EKDK6P0V4wzcB9Ajw8uy7i9URJKGG3g==,iv:+/O52rXURhzGfsay4I9uOE1gFskqg4jPC5DeRlkL7j0=,tag:lzvj46G4AqRn7S0vZIJ0tQ==,type:comment]
    #ENC[AES256_GCM,data:mrBnFVXKq2rQfR7rYOAnMyTSdILjNyHouPd//sX8CHJMIkwBrjcvPliTNn2Stjzu2C+BWdpdWqKCIJnW/vTrhGLBYQ==,iv:T3+x0EsPqSvMjmVWlvn5VEkwRkrzlwLp1K1rKal80i8=,tag:ZXRsgSjJbQmOj+BHLyyOEQ==,type:comment]
    #ENC[AES256_GCM,data:Y5JRc83Wkv3BsiUbQq22gynnZbU=,iv:X10xTJ6DzxaVNBGc6zJ08IfLIWTdXbXAi52tID99HjA=,tag:rrU2tWsfLmZbtHM/2SCTyQ==,type:comment]
    #ENC[AES256_GCM,data:VLyNrxYGwyhy5VsAREV+vcdWhYwpasvqfzrmNgg5VBNzEwDhId1Jrj7cuEsHY14=,iv:wX5zhKY2aSvMuJngqfFR322sstc6lnaXtNxLuz34mkw=,tag:363cOush5fWodRH/FJq/EQ==,type:comment]
    #ENC[AES256_GCM,data:Veb5z4bIUBFMKkmWBJcG5hgIpX7NzklbZ9X9,iv:LGNHpzHJ4fqB8WAUmJ5LpEOEeaWBogi6CnN656dKfkg=,tag:J9RgXflmJxl15NDrChkoeA==,type:comment]
    #
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:A8OPdvohmvnfU10vQ/F12fE1l5N+Q5SLtw==,iv:Y69HxNoH0N/o/v2C0C64l7x7lA+gjYydGvX1+PHe2OA=,tag:svq7fz82n/ulyw3iesFxcA==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:e6GPdEvct7s89rGS,iv:U9PzFcxFyD8mw4tMVVjYw67xgDDzcwwii8fOSK13Wuw=,tag:V/CN1tNtrX0qv2+PNoufkQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:odQ4eA9Hoq2d7ZVdmz2hB/Cai+DI+w==,iv:cR9G+t0fsptfbgHbXu5nLKPjI6SyzeQ/E9jnMNYTYkQ=,tag:6JkvZihcLpGEWWzpDT++GA==,type:str]
    OAUTH2_PROXY_OIDC_ISSUER_URL: ENC[AES256_GCM,data:yTyooz1v66H1oU/wkOkUoBRukc8YFHebInSb0il9zh7n9dSyLJvCd27u,iv:NXZyhCy3qR9zEgWuWe8/2ZVXcAq3LqScODg6JqOCP8w=,tag:50geuXWgMTxTG12B/1tsyw==,type:str]
    #ENC[AES256_GCM,data:eK5WOAYG8aXMq2t1wqDJouFmq4L71adxmheWCcKC69KCv2JGbl6bVAwoFxzh+enKBpynRfiAy6Jo,iv:i5IPm7KSLLOD3/ksQ/7/TkSabEedCZ04hpWZAi+hWww=,tag:vnV/f6LXWgDo6Kt2lRjo7Q==,type:comment]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:bwWYiXmpBykNK+vAceapzKNpF44UgkXphL3g07+7A/eXcxLfTBkrftMqTPg=,iv:n/i7tFV0j/zvBTMLBZTilX8374q6rcfY2OlWnrAQjbg=,tag:lMRcworDJUR34m6QQWRlZg==,type:str]
    OAUTH2_PROXY_COOKIE_DOMAIN: ENC[AES256_GCM,data:V3Nk8Rs9Eldv8uL/,iv:DEda5+KoxWYBDOOLnTdKNgig1CXD00jsSB41bzk2B8Q=,tag:f3a1mDlSk3gcd57mfPrx/w==,type:str]
sops:
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aVlJTGI3TkN0eUJzUCtZ
            YWZ4YTk2UDBBVmpCSVJORTBmNUNMMXlWUDJZCkFyYnRBNE90WVh6N21pS2s1Ymx0
            Q3hlRUpGcW83VEFIMHVKNE5SbERPWmcKLS0tIE5wakRrQWxIYnNFVmtFcmV6K3Uv
            Y281OEJqd1V6bXRIdjdraDhUTGw4elEKlxZVp0DGl6qLGpN2fIvG2SGJyimjYQZi
            AS8DlNcF+VRp6OyxvM7h4zT3fJLxE3fB0HS+vCAatwZ1qQSxUq3GFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T01:49:44Z"
    mac: ENC[AES256_GCM,data:OCL6gKM8vAshOBjzcDHphl8Kv3ifxO+uIc+QqTPaobryY7JsuRd7DdzCgxJSNye7+mGk1K6DQcCDBTzkYm1YMm/D8ZRKglMF8m9YddHf7FOSQ3raA4SjF8efAU2112qDd58UjsPlZoHhwkZmcxavUksIt6g3XN2yVhEffuEE/BQ=,iv:XekhHwCYjRwsphT1Ot7VDQ7JN22qIAasNfMChgJo3t0=,tag:l1+U8ItxNOsDNAS78jtqpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
