apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: oauth2-proxy-secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./secrets.sops.yaml
