apiVersion: v1
kind: PersistentVolume
metadata:
  name: filerun-mfox-files-pv
  namespace: web
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: filerun-mfox-files
    volumeAttributes:
      source: "//10.100.0.1/filerun_mfox"
    nodeStageSecretRef:
      name: filerun-mfox-smb-creds
      namespace: web