apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: &appname nextcloud
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`files.maxwlang.com`) || Host(`files.gotkryp.to`) || Host(`files.crust.monster`) || Host(`files.mochafox.com`)
      kind: Rule
      services:
        - name: *appname
          port: 80
      middlewares:
        - name: https-only
  tls:
    secretName: nextcloud-cert