apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pterodactyl-node-cert
spec:
  secretName: pterodactyl-node-cert
  dnsNames: 
    - overwritten-by-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-staging