apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: &appname nextcloud
spec:
  entryPoints:
    - websecure
  routes:
    - match: overwritten-by-secret
      kind: Rule
      services:
        - name: *appname
          port: 80
      middlewares:
        - name: https-only
  tls:
    secretName: nextcloud-cert
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: nextcloud-http
spec:
  entryPoints:
    - web
  routes:
    - match: overwritten-by-secret
      kind: Rule
      services:
        - name: *appname
          port: 80
      middlewares:
        - name: https-only