apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: web
  name: &appname pterodactyl-node
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: ingress-route-match
      kind: Rule
      services:
        - name: *appname
          port: 7329

  tls:
    secretName: pterodactyl-node-cert