apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  # - middleware-https-only.yaml
  - external-endpoint-pterodactyl-node.yaml
  - external-service-pterodactyl-node.yaml
  - external-certificate-pterodactyl-node.yaml
  - external-ingress-route-pterodactyl-node.yaml

replacements:
# Pterodactyl
  - source:
      kind: Secret
      name: traefik-secrets
      fieldPath: stringData.EXTERNAL_INGRESS_ROUTE_PTERODACTYL_NODE_ADDRESS
    targets:
      - select:
          kind: Certificate
          name: pterodactyl-node-cert
        fieldPaths:
          - spec.dnsNames.0
  - source:
      kind: Secret
      name: traefik-secrets
      fieldPath: stringData.EXTERNAL_INGRESS_ROUTE_MATCH_PTERODACTYL_NODE
    targets:
      - select:
          kind: IngressRoute
          name: pterodactyl-node
        fieldPaths:
          - spec.routes.0.match