apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - middleware-https-only.yaml
  - middleware-authentik-forwardauth-media.yaml

replacements:
  - source:
      kind: Secret
      name: traefik-secrets
      fieldPath: stringData.MIDDLEWARE_AUTHENTIK_FORWARDAUTH_MEDIA_ADDRESS
    targets:
      - select:
          kind: Middleware
          name: authentik-forwardauth-media
        fieldPaths:
          - spec.forwardAuth.address