apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - middleware-https-only.yaml
  - middleware-authentik-forwardauth-media.yaml
  - external-endpoint-pterodactyl-node.yaml
  - external-service-pterodactyl-node.yaml

replacements:
  - source:
      kind: Secret
      name: traefik-secrets
      fieldPath: stringData.MIDDLEWARE_AUTHENTIK_FORWARDAUTH_MEDIA_ADDRESS
    targets:
      - select:
          kind: Middleware
          name: authentik-forwardauth-media
        fieldPaths:
          - spec.forwardAuth.address
  - source:
      kind: Secret
      name: traefik-secrets
      fieldPath: stringData.EXTERNAL_INGRESS_ROUTE_PTERODACTYL_NODE_ADDRESS
    targets:
      - select:
          kind: Certificate
          name: pterodactyl-node-cert
        fieldPaths:
          - spec.dnsNames.0