apiVersion: v1
kind: Secret
metadata:
    name: traefik-secrets
type: Opaque
stringData:
    MIDDLEWARE_AUTHENTIK_FORWARDAUTH_MEDIA_ADDRESS: ENC[AES256_GCM,data:MQhJQCEZ5ZPM5PVwxIPxOzHdkuRjnkfNPf37PO0jcKJPgiQlu05MAsEcjp0r+Af89D+PKVbxTVseeuIiZMM=,iv:7a3qRnFCtvQFBLtrbaxre9usEQ1K+xr4O6/Ik81/ESo=,tag:9HhWykloJY8iZFJOx/K8Dg==,type:str]
    EXTERNAL_INGRESS_ROUTE_PTERODACTYL_NODE_ADDRESS: ENC[AES256_GCM,data:vCE3LhcbO0XR4/Fjxc6+byVV,iv:uYfls5J3gNss/38sC4itGy8uDNkhUneF83llMIqWWCA=,tag:SuMMzfkD6YB1UDllAbAZ9A==,type:str]
    EXTERNAL_INGRESS_ROUTE_MATCH_PTERODACTYL_NODE: ENC[AES256_GCM,data:uKwWlo1tOtcdOXJVJu+WZUJh2RaeLDpBS30=,iv:fcbooiaLpmVk1q/qNbsX1B+CYV5qw5qlzpzHw/WDDts=,tag:P/P8U01BlqNONGQjYqdtwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-19T02:30:31Z"
    mac: ENC[AES256_GCM,data:1Iphu7zlYeadoktbm3zZhlKqpfpEGIbSL8MlC0mx6zX+F5FOiffCMzoRt7rMmauEqO9ZJMONNLaKiEwQ9NCTztJfJ1XvSpseQkLdyafkgauH1MiaDfPxj+ABW7r4Wr5I3IcQmnVHODJeTjMg2P5J2CtL2yE5AJaKYGBhhJLONss=,iv:sFzrM5DsXAihCwpMKmyN0S3JPEURBWw3L/QvAmw5jZw=,tag:2wMsPukIm4xgHex85cq5uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
