apiVersion: v1
kind: Secret
metadata:
    name: traefik-secrets
type: Opaque
stringData: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSUozYkIxTWRHeG5xY2Vp
            WkVzOW5STkpDdkszSGdwWTh5eTl6TDkrSFZ3ClBWdm11UUJkVzJ6VTdZMVhNbGdm
            bmlhbHQ5eXZOWFI4OHVwQzU5aXhGSTQKLS0tIEo0eEpDc3U3UzBzK21mVzVDOUV4
            a3dkL0hJekFOcDlKMFJ5RGxXcThJR2cKo3PZpQkIxJu9Yy9KfiMp4hcLh9/oXwy5
            aQPNaRBvgy7jQ1emVupLDNs0zCfGOVfXVUVWiHfkcGRrhjkzW39jlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T03:25:35Z"
    mac: ENC[AES256_GCM,data:FqSRmF4nf9edpu6dKl23B+iR5stiqCAAEjn1RkWcaEXQZYkE5vesBa32cr+HAt6EhbTmouja3z2hA9RNR+EFf3qVqG38QXJA+cutQZ/pkGTwfZhLT7sp6qqali6Swv5LB3zlAq6P7dEVZtvioniOcxbWzQz1DYnEY/pwxPWSoH8=,iv:xFx15az37O/hxB4IoHleY2qnopR9IxB5AJyhVh/zj5E=,tag:X6/yNPZK9OrmuQkFoiPzJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
