apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml

generators:
  - secret-generator.yaml

replacements:
  - source:
      kind: Secret
      name: prowlarr-secrets
      fieldPath: stringData.INGRESS_ROUTE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: prowlarr
        fieldPaths:
          - spec.routes.0.match