apiVersion: v1
kind: Secret
metadata:
    name: s4c-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:aF+hbg0/8WHyrCq/BMG5sgTv9NIj85S7UzKQdz6stKNxKMUK+7oy00tk26a1cJAY8mFRU0QB,iv:afALz51R0PtC1kQXLuGvYLmIMINy4IAIn774O+aofm8=,tag:VciQXJD4Njow5UYMqbbqlA==,type:str]
    S4C_URI: ENC[AES256_GCM,data:qCaj8KzRdiHCj933ll8e,iv:VA1JYiIjNMdiUI6FlzaxAyfOCzvhQjP6M+SBnTZeS/o=,tag:xzZNEQfuvurO77XH2aEvpA==,type:str]
    S4C_URI_WWW: ENC[AES256_GCM,data:gWPrZ3uVMhYtSEC6CSOoX+2WZw==,iv:QZ6Fq0OMbyn/gH+HI1wN3kLZlBkO+bsFwA1PSEmvEcY=,tag:yJ6rA4tf03fivs+Ibp63aA==,type:str]
    IMAGE: ENC[AES256_GCM,data:HrReuxN2o/pf4aeCouoMcNM1HnSBQ1TLmiqY2auckdh/zOgIBHSQ,iv:dc1cuRs+wuj2KuAbWftN8qA62/Nm6qDiEwrDBGkgwVM=,tag:lTbTI0LetYbCLtexX4/iFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMHZISDZlbzIvbmxWQUlv
            ZjFORW1Wa0dSNDRWMStodWR3U29mVTN3cHpNCklMYUZrdm5FbTJUTHBVYmM1YWVF
            MkZpQ0FjMmxIaXlnOVNSOWl4T2dsNzQKLS0tIHdZWnRGS3l4dnRCU0xSVkpSZ3la
            TVVBbVduc29ZbFo4WHpPa2tseVBFV2MKTqn3p3gKsn7rKwD+j72hXH33BnHseUV+
            PSQ6OTxbEfB0RvCHr+nPZk5/Zj4UTH1Pte/ErLfa5R60RWXRilDsPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-11T04:54:56Z"
    mac: ENC[AES256_GCM,data:c+OTOvdOKaqq2LwX16MetRI4NP7n1is597HEapSyAdx3Lv8qPFWTv8xyYy7JRsCCyjdBb1RbecTw+PGMANel9FxzJ9SfmN63CWuHjw7EXAKACHzilIHfouRRRa2cc/xLOzNCdL3UB2/WVBg0SEC9ozoR5Dr5ZXkyj6sv3WPccpY=,iv:dBi1t/BJrpObzIM1IzMiY8gGZHK9L9K9hD1wwBonOAM=,tag:owdky80qN4N/9oASlx5ZmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
