apiVersion: v1
kind: Secret
metadata:
    name: s4c-secrets
type: Opaque
stringData:
    INGRESS_ROUTE_MATCH: ENC[AES256_GCM,data:aF+hbg0/8WHyrCq/BMG5sgTv9NIj85S7UzKQdz6stKNxKMUK+7oy00tk26a1cJAY8mFRU0QB,iv:afALz51R0PtC1kQXLuGvYLmIMINy4IAIn774O+aofm8=,tag:VciQXJD4Njow5UYMqbbqlA==,type:str]
    IMAGE: ENC[AES256_GCM,data:tVBY2g6+Qeq/JsEAHvvXPgL79wTcLhCky9raHEoR/JD9fPGQWcwh,iv:00/6aD4rHE9G93Lxl8+T5LB97m2gSDNwZTFF2rZcYpE=,tag:DiDp6EbljjawCkcLz+ST+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age108e7c3eh9x9gva8kswlqj4t0z3yzq6876c2qvd0z6jh3k5duggts7a90qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMHZISDZlbzIvbmxWQUlv
            ZjFORW1Wa0dSNDRWMStodWR3U29mVTN3cHpNCklMYUZrdm5FbTJUTHBVYmM1YWVF
            MkZpQ0FjMmxIaXlnOVNSOWl4T2dsNzQKLS0tIHdZWnRGS3l4dnRCU0xSVkpSZ3la
            TVVBbVduc29ZbFo4WHpPa2tseVBFV2MKTqn3p3gKsn7rKwD+j72hXH33BnHseUV+
            PSQ6OTxbEfB0RvCHr+nPZk5/Zj4UTH1Pte/ErLfa5R60RWXRilDsPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-24T07:53:00Z"
    mac: ENC[AES256_GCM,data:Cg2Kngg9HJOERcJyUY0pa79R8Gy2CFNNbZaDcdwi0wkNtXABH+T//++pXIBMvxLzKDGgFN4nEEWGrbl1aEjj8tRaXjF0BEwMe4EcEqQD6nCXBtMY+qnLWVooyB1mjyVGDJS35JxB7Fz66ZIK5UASef9nqm7ubg12F4hlD1+aW8I=,iv:yHYwvGKYEYBYSDIPLCHFn5c6nhG4lmdh5ki/IDQGeqE=,tag:BI0TRMo/TvUqKFZIyV6+PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
